### ISSUE TITLE
Support for PowerPC64 on FreeBSD

### ISSUE THREAD

**Issue by lenoil98** [thepowersgang/mrustc#100]
Since there's native support in rust for PowerPC on Linux and NetBSD.  Is there a way to leverage this to bootstrap rustc on FreeBSD/PowerPC64?

**Comment by thepowersgang** [comment]
It may be easier to just add FreeBSD+PPC64 support to rustc (you'll have to do that even if you want to use mrustc to build rustc for that target)

**Comment by lenoil98** [comment]
Thanks for the response.  I'm developing patches to add support FreeBSD+PPC64 in rustc.  I've modified mrustc so that I can test my patches.

I've been able to successfully build what seems to be a working rustc using mrustc.  The initial build completes successfully.  However, I'm having issues when building cargo.  When executing "gmake -C run_rustc" the build errors when linking  "libserde_derive-1_0_6.hir.o".

**Comment by thepowersgang** [comment]
Building untested code with mrustc is not easy, you'll probably have to dig into that linker error yourself. 

Could you paste the error here, it might be something relatively simple.

**Comment by lenoil98** [comment]
Here the error. 

gmake[3]: Leaving directory '/usr/ports/tmp/mrustc/tools/minicargo'
tools/bin/minicargo rustc-1.19.0-src/src/libstd --script-overrides script-overrides/stable-1.19.0-linux/ --output-dir output/ 
tools/bin/minicargo rustc-1.19.0-src/src/libpanic_unwind --script-overrides script-overrides/stable-1.19.0-linux/ --output-dir output/ 
tools/bin/minicargo rustc-1.19.0-src/src/libtest --vendor-dir rustc-1.19.0-src/src/vendor --output-dir output/ 
tools/bin/minicargo lib/libproc_macro --output-dir output/ 
mkdir -p output/cargo-build
tools/bin/minicargo rustc-1.19.0-src/src/tools/cargo --vendor-dir rustc-1.19.0-src/src/vendor --output-dir output/cargo-build -L output/ 
BUILDING serde_derive from serde_derive v1.0.6 with features []
> /usr/ports/tmp/mrustc/bin/mrustc rustc-1.19.0-src/src/vendor/serde_derive/src/lib.rs --crate-name serde_derive --crate-type proc-macro --crate-tag 1_0_6 -g --cfg debug_assertions -O -o output/cargo-build/libserde_derive-1_0_6.hir -L output/cargo-build --extern quote=output/cargo-build/libquote-0_3_15.hir --extern serde_derive_internals=output/cargo-build/libserde_derive_internals-0_15_0.hir --extern syn=output/cargo-build/libsyn-0_11_11.hir -L output
/usr/local/bin/ld: /tmp//ccJbhy36.o: unknown relocation type 9175131 for `*UND*'
/usr/local/bin/ld: /tmp//ccJbhy36.o: unknown relocation type 9175139 for `*UND*'
/usr/local/bin/ld: /tmp//ccJbhy36.o: unknown relocation type 9175153 for `*UND*'
/usr/local/bin/ld: /tmp//ccJbhy36.o: unknown relocation type 9175161 for `*UND*'
/usr/local/bin/ld: /tmp//ccJbhy36.o: unknown relocation type 9175172 for `*UND*'
/usr/local/bin/ld: /tmp//ccJbhy36.o: unknown relocation type 9175180 for `*UND*'
/usr/local/bin/ld: /tmp//ccJbhy36.o: unknown relocation type 9175194 for `*UND*'
/usr/local/bin/ld: /tmp//ccJbhy36.o: unknown relocation type 9175202 for `*UND*'
/usr/local/bin/ld: /tmp//ccJbhy36.o: unknown relocation type 9175213 for `*UND*'
/usr/local/bin/ld: /tmp//ccJbhy36.o: unknown relocation type 9175221 for `*UND*'
/usr/local/bin/ld: /tmp//ccJbhy36.o: unknown relocation type 9175235 for `*UND*'
/usr/local/bin/ld: /tmp//ccJbhy36.o: unknown relocation type 9175243 for `*UND*'
/usr/local/bin/ld: /tmp//ccJbhy36.o: unknown relocation type 9175254 for `*UND*'
/usr/local/bin/ld: /tmp//ccJbhy36.o: unknown relocation type 9175262 for `*UND*'
/usr/local/bin/ld: /tmp//ccJbhy36.o: unknown relocation type 9175276 for `*UND*'
/usr/local/bin/ld: /tmp//ccJbhy36.o: unknown relocation type 9175284 for `*UND*'
/usr/local/bin/ld: /tmp//ccJbhy36.o: unknown relocation type 9175295 for `*UND*'
/usr/local/bin/ld: /tmp//ccJbhy36.o: unknown relocation type 9175303 for `*UND*'
/usr/local/bin/ld: /tmp//ccJbhy36.o: unknown relocation type 9175317 for `*UND*'
/usr/local/bin/ld: /tmp//ccJbhy36.o: unknown relocation type 9175325 for `*UND*'
/usr/local/bin/ld: /tmp//ccJbhy36.o: unknown relocation type 9175336 for `*UND*'
/usr/local/bin/ld: /tmp//ccJbhy36.o: unknown relocation type 9175344 for `*UND*'
/usr/local/bin/ld: final link failed: Bad value
collect2: error: ld returned 1 exit status
C Compiler failed to execute - error code 256
BUILD FAILED
gmake[2]: *** [minicargo.mk:94: output/cargo] Error 1
gmake[2]: Leaving directory '/usr/ports/tmp/mrustc'
gmake[1]: *** [Makefile:154: output/cargo] Error 2
gmake[1]: Leaving directory '/usr/ports/tmp/mrustc'
gmake: *** [Makefile:22: ../output/cargo] Error 2

**Comment by lenoil98** [comment]
It works. Below is the output.

root@lenoil8:/usr/ports/tmp/mrustc # gmake test
bin/mrustc --target ./samples/target_stress_test.toml --dump-target-spec TMP-dump-target_stress_test.toml
Target Load: V V V
(0.00 s) Target Load: DONE
bin/mrustc --target ./TMP-dump-target_stress_test.toml --dump-target-spec TMP-dump-target_stress_test-2.toml
Target Load: V V V
(0.00 s) Target Load: DONE
diff ./samples/target_stress_test.toml TMP-dump-target_stress_test.toml
diff TMP-dump-target_stress_test.toml TMP-dump-target_stress_test-2.toml
cc -c rustc-1.19.0-src/src/rt/rust_test_helpers.c -o output/rust_test_helpers.o
ar cur output/librust_test_helpers.a output/rust_test_helpers.o
--- [MRUSTC] -o output/rust/test_run-pass_hello
bin/mrustc rustc-1.19.0-src/src/test/run-pass/hello.rs -o output/rust/test_run-pass_hello --cfg debug_assertions -g -O -L output/  2>&1 | tee output/rust/test_run-pass_hello_dbg.txt | tail -n 10 ; test ${PIPESTATUS[0]} -eq 0
(0.00 s) MIR Validate Full: DONE
Trans Enumerate: V V V
(0.00 s) Trans Enumerate: DONE
Trans Monomorph: V V V
(0.00 s) Trans Monomorph: DONE
MIR Optimise Inline: V V V
(0.00 s) MIR Optimise Inline: DONE
Trans Codegen: V V V
Running comamnd - "powerpc64-unknown-freebsd-gcc" "-ffunction-sections" "-pthread" "-O2" "-g" "-o" "output/rust/test_run-pass_hello" "output/rust/test_run-pass_hello.c" "output//libunwind.hir.o" "output//liblibc.hir.o" "output//libcollections.hir.o" "output//liballoc.hir.o" "output//liballoc_system.hir.o" "output//libcore.hir.o" "output//libpanic_abort.hir.o" "output//libcompiler_builtins.hir.o" "output//librand.hir.o" "output//libstd.hir.o" "output//libstd_unicode.hir.o" "-L" "output/" "-L" "output" "-l" "util" "-l" "c" "-l" "m" "-l" "rt" "-l" "pthread" "-l" "dl" "-l" "rt" "-l" "pthread" "-Wl,--gc-sections" 
(0.01 s) Trans Codegen: DONE
--- [output/rust/test_run-pass_hello]
hello, world

**Comment by thepowersgang** [comment]
Well, that means that it's probably related to the libraries included by `serde_derive`. You can find the command executed to build/link the executable in `output/cargo-build/libserde_derive-1_0_6.hir_dbg.txt`, which may help you figure out where those link errors are coming from.

**Comment by lenoil98** [comment]
The problem was it was using gcc7 vice gcc6 as the linker.  I've switched to gcc6 and rebuilding from the start.  Will provide updates.

**Comment by thepowersgang** [comment]
Well, it's trying to run rustc, but crashing when running it. This may be either a error in the mrustc codegen, or a bug in your rustc/std patches.

**Comment by lenoil98** [comment]
OBE
