### ISSUE TITLE
Failure to compile typenum crate

### ISSUE THREAD

**Issue by krobelus** [thepowersgang/mrustc#114]
Hi, I am trying to build a crate called [typenum](https://github.com/paholg/typenum) (I tried release 1.10.0 and HEAD) like so
(You'll also need to join the author lines in `Cargo.toml`)
```sh
minicargo . -L /path/to/mrustc/output
```

However, mrustc segfaults. It looks like `Resolve_Use_GetBinding_Mod` is calling itself indefinitely trying to lookup trait `NonZero`.
I tried to extract a minimal example and debug but without much luck.

This is with mrustc from master, should I try nightly-1.29?

**Comment by thepowersgang** [comment]
Confirmed with master.
 `nightly-1.29` does pass the resolve stage (not triggering the bug) but then falls over with a defaulted type parameter later on.

**Comment by thepowersgang** [comment]
Current error: `Resolve UFCS paths` fails with an assertion in checking a trait bound using a default type parameter.

**Comment by thepowersgang** [comment]
Closing: Works with current master f89824b5bfb6902dff93f63cc146f3b5b247833a
