### ISSUE TITLE
Please avoid using $V in Makefiles

### ISSUE THREAD

**Issue by glaubitz** [thepowersgang/mrustc#115]
Multiple Makefiles are using the variable $V to prefix $CXX.

I'm not sure what the exact intention of this is, but it causes problems when building ```mrustc``` as an RPM package. This is becasue ```rpmbuild``` invokes ```make``` with ```V=1 VERBOSE=1``` by default, see: https://github.com/rpm-software-management/rpm/blob/master/macros.in#L1046

I had to strip "$V" from the Makefiles for my ```mrustc``` RPM package to build fine on openSUSE as otherwise, the build process tries to invoke ```1g++``` instead of ```g++```.

**Comment by thepowersgang** [comment]
The intent of the `$V` fragment is to allow removal of the `@` prefix from commands (there's a `V ?= @` line near the start of the Makefile)

A workaround could be to detect `V=1` in the makefile and set `V` to an empty string in that case.

**Comment by glaubitz** [comment]
Would it be okay to use a different variable name instead?

**Comment by thepowersgang** [comment]
Potentially.. however I'm curious as to why the RPM process assumes that `V` is always a boolean verbose flag. Do you know the intention behind passing that flag?

**Comment by glaubitz** [comment]
I think the general assumption is that ```V=1``` makes the build verbose.

**Comment by thepowersgang** [comment]
Revision 97763cebbdbe016a694840cc296c76b65576aa57 (in the nightly-1.29 branch) fixed the handling of `$V`

I'll close this issue once that branch is merged/moved to master

**Comment by glaubitz** [comment]
Okay, thanks! I‘m looking into packaging mrustc for Debian next week. I‘m currently on vacation and now have time for that ;).

**Comment by thepowersgang** [comment]
Closing, the makefile changes are now in master.
