### ISSUE TITLE
Lots of warnings about redeclaring structs as classes

### ISSUE THREAD

**Issue by ubsan** [thepowersgang/mrustc#12]

**Comment by thepowersgang** [comment]
Because gcc doesn't complain, even with -Wall :)

**Comment by ubsan** [comment]
@thepowersgang `-Wall -Wextra` :)

**Comment by thepowersgang** [comment]
Warnings should now be gone as part of a push to clean up the clang build, ref 50ef0034194c2dc1d2fb5730231c8566f405f1f6
