### ISSUE TITLE
License Compatibility Question: Possible to Dual License to GPL?

### ISSUE THREAD

**Issue by gbutler69** [thepowersgang/mrustc#120]
Hello,

There is a discussion on the Rust Internals (https://users.rust-lang.org/t/call-for-help-implementing-an-independent-rust-frontend-for-gcc/32163/25) about getting a reimplementation of Rust as a GCC front-end off the ground. There is some discussion about whether your excellent work on mrustc could be used as a bootstrap from the current Rust compiler from GCC to get then a building Rust compiler written in Rust but using the GCC back-end directly. Unfortunately, GCC governance currently requires everything shipped with GCC is GPL and copyright assigned to the GNU Foundation. Is that something you would be interested in supporting by dual licensing mrustc as MIT and GPL? Is that even possible given the contributor make-up? Would you be open to the idea at all or would you be philosophically opposed to such an idea?

Thanks for your time and consideration.

**Comment by eddyp** [comment]
@gbutler69 MIT is compatible with GPL, so any MIT licensed code can flow freely into GPL-ed code, but not the other way around. So relicensing as GPL is not necessary.

What I find problematic is assigning copyright to the FSF, which would mean that every mrustc contributor would have to agree to this, but accepting contributions to the mrustc compiler would be conditioned by accepting the copyright reassignment. More than that, once assigned, only the FSF would have the power to change the license if a more permissive license is desired (e.g. to combine with code with a copy-left GPL-incompatible license such as the CDDL - say some part of OpenZFS is to be rewritten in Rust, or the BSD world which prefers permissive licenses).

Even if I am not in any way a contributor of mrustc, I would advise against the proposed changes. Of course, I am just some dude, @thepowersgang and others might have a different opinion

**Comment by gbutler69** [comment]
> What I find problematic is assigning copyright to the FSF,

Not to minimize this concern at all, but, to clarify, this is only giving FSF copyright to the code so they ALSO have full copyright to relicense it in the future to newer GPL versions that might arise to close holes in the license. You, and all the other contributors, still maintain your own full copyright and are free to use the original code however you like. The only thing prevented is as the GPL version diverges from your version (which is almost necessarily in this case the intent), you would not be able to merge it back into a non-GPL version (but, that doesn't seem like a desirable result anyways). Also, in the case of the MIT license that you've used, I don't believe copyright assignment is required because the MIT license is completely compatible with distribution with GPL code as well. 

>> Even if I am not in any way a contributor of mrustc, I would advise against the proposed changes

To  be clear nothing needs to change about the license of the mrustc project. Mrustc need not change its license in any way. The linked discussion clarifies (counter to what I mentioned in the orginal text of this issue) that Copyright assignment and relicensing to GPL is not required; however, if the mrustc developers would consider dual-licensing mrustc as both MIT and/or GPL, it would make it even easier and more compatible to use as a starting point for an independent GPL/GCC version of Rust.

It is completely understandable  if that is not something the current mrustc contributors are interested in or would prefer, but, I didn't feel it would be appropriate to talk too much about mrustc as a possible boot-strap solution without the input from the current mrustc developers.

**Comment by thepowersgang** [comment]
I'm pretty comfortable with MIT, as you'd guess. And as pointed out above, a relicence isn't required for packaging with GCC.

Closing issue for now.

**Comment by illiliti** [comment]
FYI, gcc no longer requires copyright assignment -> https://lwn.net/Articles/857791/
