### ISSUE TITLE
Provide a way to check rustc compatibility

### ISSUE THREAD

**Issue by elichai** [thepowersgang/mrustc#122]
A lot of crates these days are checking for rustc version: https://github.com/rust-lang/libc/blob/master/build.rs#L77

Adding the `RUSTC`  env var is super easy[1]. but then looking at the code there it's obious that by splitting with `.` the first part won't be `rustc 1`.
how can we expose the correct `rustc` compatibility version? maybe adding a `--rustc-version` flag and then we can go patch crates that check for rustc version to support mrustc too. (maybe not adding a `RUSTC` envvar but adding a `MRUSTC` instead? )

Would love to hear what people think.

[1] 
```
diff --git a/tools/minicargo/build.cpp b/tools/minicargo/build.cpp
index 53fa1a16..e2035bb3 100644
--- a/tools/minicargo/build.cpp
+++ b/tools/minicargo/build.cpp
@@ -750,6 +750,7 @@ bool Builder::build_target(const PackageManifest& manifest, const PackageTarget&
     env.push_back("CARGO_PKG_VERSION_MAJOR", ::format(manifest.version().major));
     env.push_back("CARGO_PKG_VERSION_MINOR", ::format(manifest.version().minor));
     env.push_back("CARGO_PKG_VERSION_PATCH", ::format(manifest.version().patch));
+    env.push_back("RUSTC", ::format(this->m_compiler_path));
     for(const auto& dep : manifest.dependencies())
     {
         if( ! dep.is_disabled() )

```

**Comment by thepowersgang** [comment]
Using an argument sounds like a good idea. Currently the `nightly-1.29` branch uses an environment variable to change which version mrustc assumes (between 1.19 and 1.29)

**Comment by thepowersgang** [comment]
Further invesigation (testing on a machine with no rustc installed) shows that the existing environment variable could work just as well.

For just pretending to be rustc, mrustc's `--version` output could say (e.g.) `rustc 1.29.100 (mrustc 0.9 master:abd2a151)` when running in 1.29 mode.

**Comment by thepowersgang** [comment]
The `nightly-1.29` branch now has this feature (as of e7da7df99a3597cfdc8fa0feca970f54736dc866), will close this issue once that branch is reintegrated into `master`.

**Comment by thepowersgang** [comment]
Closing: The requisite changes have been merged into master.
