### ISSUE TITLE
[Question] Is it possible to build Firefox with it?

### ISSUE THREAD

**Issue by protonesso** [thepowersgang/mrustc#128]
Hi, I found your compiler implementation. It seems small and I wondering is it possible to build recent Firefox with it?

**Comment by bjorn3** [comment]
mrustc only supports bootstrapping rust 1.19 and 1.29. I believe the last firefox building with that is firefox 64, released just before the start of 2019. Even for that version it is likely that you will still need to build rustc 1.29 itself using mrustc to be able to compile firefox, as mrustc only implements features required to bootstrap rustc.

**Comment by thepowersgang** [comment]
As @bjorn3 implied - Quite unlikely that it is possible, but you're welcome to give it a try.

mrustc is pretty complete (as rustc/cargo use a lot of interesting compiler features), but there's always edge cases where type inferrence falls over (or something else breaks).

**Comment by protonesso** [comment]
will test soon

**Comment by protonesso** [comment]
@thepowersgang trying to port your compiler on rust 1.44.1, and when compiling libstd it says this:
```
./bin/minicargo rustc-1.44.1-src/src/libstd/                                                                                                                                                                    
> /home/yuyu/ataraxia/packages/mrustc/work/src/mrustc-84b22a9c8b16a96491b896e76e7da4834e96c439/bin/mrustc -Z print-cfgs
EXCEPTION: Unable to find a manifest for compiler_builtins:^0.1.10
```

**Comment by protonesso** [comment]
Patch is mrustc.patch and rust.patch, can be found here: https://github.com/ataraxialinux/ataraxia/tree/master/stuff/mrustc

Also I wanted musl support

**Comment by thepowersgang** [comment]
Well, step 1 is don't try to use 1.44 - use 1.29 or 1.19. 1.39 support is in progress, but is a lot of work.

**Comment by protonesso** [comment]
oh

**Comment by protonesso** [comment]
Anyway, maybe some patches can help, at least with llvm :)

**Comment by concatime** [comment]
@protonesso I’m on musl too. I’ve faced this: https://github.com/thepowersgang/mrustc/issues/166 with Rust 1.29. Will wait for 1.39 because support was only added in 1.35: https://github.com/rust-lang/rust/blob/master/RELEASES.md#misc-11. We should probably give it a try when @thepowersgang would complete the support of 1.39.
