### ISSUE TITLE
[Question] Is it possible to build Linux kernel modules with mrustc?

### ISSUE THREAD

**Issue by tschwinge** [thepowersgang/mrustc#130]
Similar to #128, I'm curious if anyone has attempted/succeeded/failed to build Linux kernel modules with mrustc?  (I can't right now but shally give it a try at some point, but I'm curious already.)

References: <https://lwn.net/Articles/797558/>, <https://github.com/tsgates/rust.ko>, <https://github.com/lizhuohua/linux-kernel-module-rust>, <https://github.com/fishinabarrel/linux-kernel-module-rust>, <https://gitlab.com/ra_kete/kmod-rs>, etc.

**Comment by thepowersgang** [comment]
Quite likely possible, might be an expirence to do the building though (mrustc isn't the nicest compiler to use)
