### ISSUE TITLE
Test failure in mrustc 0.9 - enums - Borrow

### ISSUE THREAD

**Issue by daym** [thepowersgang/mrustc#137]
```
$ make local_tests
[...]
Calling mrustc -O -L output -o output/local_tests/enums.exe samples/test/enums.rs                                                                                   
Target Load: V V V
(0.00 s) Target Load: DONE
Parse: V V V
(0.00 s) Parse: DONE
LoadCrates: V V V
(0.19 s) LoadCrates: DONE
Expand: V V V
(0.00 s) Expand: DONE
Implicit Crates: V V V
(0.00 s) Implicit Crates: DONE
Resolve Use: V V V
(0.00 s) Resolve Use: DONE
Resolve Index: V V V
(0.00 s) Resolve Index: DONE
Resolve Absolute: V V V
(0.00 s) Resolve Absolute: DONE
HIR Lower: V V V
(0.00 s) HIR Lower: DONE
Resolve Type Aliases: V V V
(0.00 s) Resolve Type Aliases: DONE
Resolve Bind: V V V
(0.05 s) Resolve Bind: DONE
Resolve HIR Markings: V V V
(0.00 s) Resolve HIR Markings: DONE
Resolve UFCS Outer: V V V
(0.00 s) Resolve UFCS Outer: DONE
Resolve UFCS paths: V V V
(0.00 s) Resolve UFCS paths: DONE
Constant Evaluate: V V V
(0.00 s) Constant Evaluate: DONE
Typecheck Outer: V V V
(0.00 s) Typecheck Outer: DONE
Typecheck Expressions: V V V
(0.00 s) Typecheck Expressions: DONE
Expand HIR Annotate: V V V
(0.00 s) Expand HIR Annotate: DONE
Expand HIR Closures: V V V
(0.00 s) Expand HIR Closures: DONE
Expand HIR VTables: V V V
(0.00 s) Expand HIR VTables: DONE
Expand HIR Calls: V V V
(0.00 s) Expand HIR Calls: DONE
Expand HIR Reborrows: V V V
(0.00 s) Expand HIR Reborrows: DONE
Expand HIR ErasedType: V V V
(0.00 s) Expand HIR ErasedType: DONE
Typecheck Expressions (validate): V V V
(0.00 s) Typecheck Expressions (validate): DONE
Lower MIR: V V V
samples/test/enums.rs:12: BUG:src/mir/from_hir_match.cpp:1460: Matching borrow invalid pattern - 1
samples/test/enums.rs:12: note: From here
```

**Comment by bjorn3** [comment]
Can you please post the test code?

**Comment by daym** [comment]
It's part of that mrustc release.

```
enum Values
{
    One,
    Two,
    Three,
}

fn main()
{
    assert!(match Some(&1) { Some(1) => true, _ => false });
    assert!(match Some(1) { Some(1) => true, _ => false }); // <--- here
    assert!(match Values::One { Values::One => true, _ => false });
}
```

**Comment by thepowersgang** [comment]
Hmm... https://travis-ci.org/thepowersgang/mrustc/jobs/606372355 worked (the 0.9 tagged version) as does the most recent build.

**Comment by tschwinge** [comment]
I too cannot reproduce this, neither with v0.9, nor with current master.

**Comment by daym** [comment]
Apparently travis uses gcc 6. We are trying gcc 7.4.0. I'll try gcc 6 shortly.

**Comment by daym** [comment]
Nope, with gcc 6.5 too,

DEBUG: COMPILE FAIL enums, log in output/local_tests/enums.exe-build.log
11 passed, 0 failed, 1 errored, 0 skipped

**Comment by tschwinge** [comment]
Hmm.  I still cannot reproduce this, building stuff with `env CC=gcc-7 CXX=g++-7 CC-x86_64-linux-gnu=gcc-7 make [...]`, with that being `gcc-7 (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0`.

You're on x86_64-linux-gnu, too, right?

**Comment by daym** [comment]
Yes.

**Comment by daym** [comment]
When I call the test outside the container, I get

Typecheck Expressions: V V V
:0: error:0:Undefined language item 'clone' required
samples/test/enums.rs:12: note: From here

**Comment by daym** [comment]
Switching compilers some more, I get the following warning:

```
src/ast/path.cpp:205:56: warning: ‘void* memcpy(void*, const void*, size_t)’ writing to an object of type ‘struct AST::Path::Bindings’ with no trivial copy-assignment [-Wclass-memaccess]
  205 |     memcpy(&m_bindings, &x.m_bindings, sizeof(Bindings));
```

**Comment by daym** [comment]
Exactly the same happens on armhf on Ubuntu 19.10.

**Comment by thepowersgang** [comment]
Tested HEAD with `gcc (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0`, could not reproduce.

Could you provide the contents of `output/local_tests/enums.exe-build.log` with `MRUSTC_DEBUG="Lower MIR"` set?

(Side note - I assume the text in the initial post was the contents of that file? It shouldn't be being printed to stdout when run from the test runner)

**Comment by thepowersgang** [comment]
Wait -- Do you have `MRUSTC_TARGET_VER` set to `1.19.0`? That will make the compiler not accept the code in that test.

**Comment by daym** [comment]
@thepowersgang:

>(Side note - I assume the text in the initial post was the contents of that file? It shouldn't be being printed to stdout when run from the test runner)

Yes.

>Wait -- Do you have MRUSTC_TARGET_VER set to 1.19.0? That will make the compiler not accept the code in that test.

Hmm, then what's the recommended way to build a bootstrapper for rust 1.19.0 ?

**Comment by thepowersgang** [comment]
See if rustc/cargo build and run. (that's how I tend to test)

**Comment by daym** [comment]
Okay.

Thanks for your help!
