### ISSUE TITLE
Build failed, Unknown target name ''

### ISSUE THREAD

**Issue by Michele31415** [thepowersgang/mrustc#139]
I know, I'm trying to do this on a Sun T4-1 in Solaris 11.4 SPARC.  But things seemed to be going along well and I even got an mrustc executable.  But during the build it goes: 

```
root@hemlock:~/mrustc/mrustc# gmake RUSTC_TARGET=x86-windows-msvc -f minicargo.mk
gmake -f Makefile all
gmake[1]: Entering directory '/export/home/michele/mrustc/mrustc'
gmake[1]: Nothing to be done for 'all'.
gmake[1]: Leaving directory '/export/home/michele/mrustc/mrustc'
gmake -C tools/minicargo/
gmake[1]: Entering directory '/export/home/michele/mrustc/mrustc/tools/minicargo'
gmake[1]: Nothing to be done for 'all'.
gmake[1]: Leaving directory '/export/home/michele/mrustc/mrustc/tools/minicargo'
tools/bin/minicargo rustc-1.19.0-src/src/libstd --script-overrides script-overrides/stable-1.19.0-linux/ --output-dir output/ 
BUILDING core from core v0.0.0 with features []
> bin/mrustc rustc-1.19.0-src/src/libcore/lib.rs --crate-name core --crate-type rlib -g --cfg debug_assertions -O -o output/libcore.hir -L output
Unknown target name ''
BUILD FAILED
gmake: *** [minicargo.mk:64: output/libstd.hir] Error 1
root@hemlock:~/mrustc/mrustc# 
```

The target supplied in the command line is one listed in src/trans/target.cpp.  Who's not picking up the target?

**Comment by thepowersgang** [comment]
You need to also set `MINICARGO_FLAGS=--target x86-windows-msvc`

It's using a blank string because the `tools/common/target_detect.h` header doesn't know about Solaris (it should have emitted a warning while compiling, and defaults to a blank string)

**Comment by Michele31415** [comment]
Thanks!  That took care of that but now I'm getting:

root@hemlock:~/mrustc/mrustc# MINICARGO_FLAGS="--target x86-windows-msvc"
root@hemlock:~/mrustc/mrustc# export MINICARGO_FLAGS
root@hemlock:~/mrustc/mrustc# gmake RUSTC_TARGET=x86-windows-msvc -f minicargo.mk
gmake -f Makefile all
gmake[1]: Entering directory '/export/home/denber/mrustc/mrustc'
gmake[1]: Nothing to be done for 'all'.
gmake[1]: Leaving directory '/export/home/denber/mrustc/mrustc'
gmake -C tools/minicargo/
gmake[1]: Entering directory '/export/home/denber/mrustc/mrustc/tools/minicargo'
gmake[1]: Nothing to be done for 'all'.
gmake[1]: Leaving directory '/export/home/denber/mrustc/mrustc/tools/minicargo'
tools/bin/minicargo rustc-1.19.0-src/src/libstd --script-overrides script-overrides/stable-1.19.0-linux/ --output-dir output/ --target x86-windows-msvc
BUILDING core from core v0.0.0 with features []
> bin/mrustc rustc-1.19.0-src/src/libcore/lib.rs --crate-name core --crate-type rlib -g --cfg debug_assertions -O --target x86-windows-msvc -C emit-build-command=output/libcore.hir.sh -o output/libcore.hir -L output
MIR ERROR: ::"core"::sync::atomic::atomic_compare_exchange<i32,> BB12/TERM: Unsupported atomic type - i32
BUILD FAILED
gmake: *** [minicargo.mk:64: output/libstd.hir] Error 1
root@hemlock:~/mrustc/mrustc# 

I suspect this may have something to do with the fact that I'm on a 64 bit platform but I don't know what to do about it.  Also, would it be legal to just add a line in target_detect.h to the effect of
define DEFAULT_TARGET_NAME "sparcv9-sun-solaris"
?  (Since that is apparently a valid Tier 2 target name).

**Comment by thepowersgang** [comment]
(Tip: Surround code with ` ``` ` - it makes the formatting easier to read)

Just having the target name isn't enough, mrustc needs to know about the target. However, this error isn't from that problem.

You appear to be using an older version of mrustc, the current version supports atomics on MSVC.

**Comment by Michele31415** [comment]
Thanks for the tip.  I did select the code and then click on the "<>" icon but I guess that's not working, probably because I have to use Firefox 52, which is why I'd like to get Rust, so I can compile a new Firefox.

I downloaded mrustc from a link I've lost now.  From where should I be downloading it?  I have no problem starting over.

And if I may ask a dumb question - does "target" refer to the platform on which mrustc is being built or the platform for which the compiler will be creating code for?  I'm working in Solaris 11.4 SPARC and want my compiler to make code for that same platform too.

**Comment by thepowersgang** [comment]
Target is the plaform it's creating code for (i.e. the compilation target).

You should be getting at least the latest tagged release on github, but the current `HEAD` should usually work.

**Comment by Michele31415** [comment]
OK, I downloaded mrustc-master.zip from github.  After unzipping, it contains a file rust-version which contains the string 1.29.0.  Is this the file I should be using?

And to cut to the chase, is it going to be possible at all to get this going with a target of sparcv9-sun-solaris or am I barking up yet another wrong tree?  I've read that the Rust community depnds on contributers.  I'd be happy to contribute but I need at least a little clue.  Thanks.

**Comment by thepowersgang** [comment]
Does rustc (the official compiler) support that target?
If it does, the you might be able to get some luck (you will have to write a mrustc target spec, either as a toml file or by editing `target.cpp`).

**Comment by Michele31415** [comment]
In https://forge.rust-lang.org/release/platform-support.html there is a line in Tier 2 for:
sparcv9-sun-solaris	\u2713			SPARC Solaris 10/11, illumos
The check mark means that "only the standard library is compiled".  So apparently there is some acknowledgment of SPAR C Solaris over there.

Modifying target.cpp looks hard so I looked at the page https://github.com/thepowersgang/mrustc/blob/master/docs/target.md   That gives some hints as to how to make a custom toml file but not enough (for me at least) to figure it out.  Where should my custom file go?  What should it be named?  And if I do this then I don't need to do anything to target.cpp?

Let me also test, since the "<>" button doesn't work, if I can use three backquotes to make a code segment:
```Does this line come out as code?```

**Comment by thepowersgang** [comment]
(Single backticks for a line, triple for a block)

So, quick clarification - Do not expect mrustc to work out of the box for anything other than amd64 linux.

On to the actual questions:
- The quick way to get a target file you can fiddle with (I'll add this to the docs) is `./bin/mrustc --dump-target-spec default_target.toml`
- Then, edit that to match the options required for your target (and maybe rename it to `sparcv9-sun-solaris.toml`)
- And then set `MINICARGO_FLAGS="--target sparcv9-sun-solaris.toml"` when compiling.

**Comment by Michele31415** [comment]
Maybe I'm doing something wrong but that didn't work for me:

```root@hemlock:~/mrustc/mrustc/bin# ./mrustc --dump-target-spec default_target.toml
Unknown option '--dump-target-spec'
root@hemlock:~/mrustc/mrustc/bin# ```

Another problem while running minicargo.mk:

`date: illegal option -- R`

Apparently Solaris date does not have the R flag.  I tried compiling a Linux date.c for Solaris but it had a bunch of missing .h files.  I tried to ggrep the mrustc directory for "date -R" but came up empty.  Do you know who is calling date -R?

**Comment by thepowersgang** [comment]
for `date` - It's the rule for `version.o` in `Makefile`

for `--dump-target-spec` - What version of mrustc are you building?

**Comment by Michele31415** [comment]
Ah!  That's why ggrep couldn't find it.  The string  (in loine 303) is actually "shell date -uR)".  I just removed the -R and tried again.

```root@hemlock:~/mrustc1/mrustc-master# gmake RUSTC_TARGET=x86_64-unknown-freebsd -f minicargo.mk
gmake -f Makefile all
gmake[1]: Entering directory '/export/home/michele/mrustc1/mrustc-master'
fatal: Not a git repository (or any parent up to mount point /export/home)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
fatal: Not a git repository (or any parent up to mount point /export/home)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
fatal: Not a git repository (or any parent up to mount point /export/home)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
fatal: Not a git repository (or any parent up to mount point /export/home)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
fatal: Not a git repository (or any parent up to mount point /export/home)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
[CXX] -o .obj/version.o
[AR] -o bin/mrustc.a
ar: bad option: -D
usage:
    ar -d [-SvV] archive [file...]
    ar -m [-SvV] [-{a|b|i} posname] archive [file...]
    ar -p [-sSvV] archive [file ...]
    ar -q [-cSvV] archive [file...]
    ar -r [-cSuvV] [-{a|b|i} posname] archive [file...]
    ar -t [-sSvV] archive [file...]
    ar -x [-CsSTvV] archive [file...]
    ar [-sSvV] archive
gmake[1]: *** [Makefile:283: bin/mrustc.a] Error 1
gmake[1]: Leaving directory '/export/home/michele/mrustc1/mrustc-master'
gmake: *** [minicargo.mk:60: bin/mrustc] Error 2
root@hemlock:~/mrustc1/mrustc-master# ```

It looks now like solaris ar doesn't have the -D switch.  And I don't know what this "not a git repository" error means.  At least it's getting further along :-)

"for --dump-target-spec - What version of mrustc are you building?"
The latest one from github - 1.29.  Perhaps the problem is this:

```root@hemlock:~/mrustc1/mrustc-master# find . default_target | grep default_target
find: stat() error default_target: No such file or directory
root@hemlock:~/mrustc1/mrustc-master# ```

**Comment by thepowersgang** [comment]
(Note: the ` ``` ` needs to be on its own line - Use the "Preview" tab to check your formatting)

That explains why the `--dump-target-spec` didn't work - `mrust` didn't rebuild. The `git` errors are because the build scripts expect to be run from a git checkout. They should be benign... it's the link error that's the problem. Looks like the `ar` you have is not quite compatible with gnu binutils.

**Comment by Michele31415** [comment]
It appears that ar is being called on line 283 of Makefile:
	`$Var rcD $@ $(filter-out $(OBJDIR)main.o, $(OBJ))`
Apparently D means use "deterministic" mode and that may already be the default depending on how binutils was compiled.  I'm using binutils from OpenCSW and I have no idea how they were compiled but I figure it's a 50-50 shot.  I was unable to find an ar for Solaris that had -D and determinism didn't seem all that critical to me so in the interest of expediency I just removed the D and that allowed us to go further:
```...
[CXX] debug.cpp
[AR] rcu ../bin/common_lib.a
gmake[2]: Leaving directory '/export/home/michele/mrustc1/mrustc-master/tools/common'
[CXX] -o bin/mrustc
objcopy --only-keep-debug bin/mrustc bin/mrustc.debug
bash: objcopy: command not found
gmake[1]: *** [Makefile:289: bin/mrustc] Error 127
gmake[1]: Leaving directory '/export/home/michele/mrustc1/mrustc-master'
gmake: *** [minicargo.mk:60: bin/mrustc] Error 2
root@hemlock:~/mrustc1/mrustc-master# 
```
So now I need to find an objcopy.

(Thanks for the Preview tip but that button doesn't work in FF 52 either.)

**Comment by Michele31415** [comment]
Oops - objcopy is included in binutils (actually it's supposed to be in Solaris 11.4 but I can't find it) so I just added /opt/csw/bin to PATH.  Now we're getting somewhere:

```root@hemlock:~/mrustc1/mrustc-master# gmake RUSTC_TARGET=x86_64-unknown-freebsd -f minicargo.mk
...
[CXX] repository.cpp
[CXX] cfg.cpp
[CXX] -o ../bin/minicargo
gmake[1]: Leaving directory '/export/home/michele/mrustc1/mrustc-master/tools/minicargo'
test -e tools/bin/minicargo
tools/bin/minicargo rustc-1.29.0-src/src/libstd --script-overrides script-overrides/stable-1.29.0-linux/ --output-dir output/ 
> bin/mrustc -Z print-cfgs
Unknown target name ''
Process was terminated with signal 6
EXCEPTION: Unable to invoke compiler to get config options
gmake: *** [minicargo.mk:71: output/libstd.rlib] Error 1
root@hemlock:~/mrustc1/mrustc-master# 
```
Not sure what to do with "target" here.

**Comment by bjorn3** [comment]
Try removing https://github.com/thepowersgang/mrustc/blob/master/Makefile#L291-L293 or adding a conditional to not run it on solaris.

**Comment by Michele31415** [comment]
I'm not sure which problem you were referring to but I pulled those lines out and ran 
`root@hemlock:~/mrustc1/mrustc-master# gmake RUSTC_TARGET=x86_64-unknown-freebsd -f minicargo.mk`
again but with the same results as above (unknown target name '').  I'm guessing this is because I don't have a target specified for Solaris and I don't know how to make one.  On the plus side I do now have an executable called mrustc in bin.

**Comment by bjorn3** [comment]
I was refering to the objcopy problem. I didn't see your last comment until I had already pressed comment.

**Comment by Michele31415** [comment]
Ah, OK thanks.  Could you please give me a hint as to how to fix that unknown target problem?  Will making a target.toml file for SPARC fix it?  And how do I do that?  Would something like this suffice? (Copied and modified from https://github.com/japaric-archived/cu/blob/9d7ebc8daf16f61eacd5df2afa48445e6ca23198/cortex-m3.json)

```{
    "arch": "sparc",
    "cpu": "sunv9",
    "data-layout": "e-m:e-p:32:32-i64:64-v128:64:128-a:0:32-n32-S64",
    "executables": true,
    "linker": "arm-none-eabi-gcc",
    "llvm-target": "thumbv7m-none-eabi",
    "no-compiler-rt": true,
    "os": "none",
    "pre-link-args": ["-Tstm32f100.ld", "-nostartfiles"],
    "relocation-model": "static",
    "target-endian": "big",
    "target-pointer-width": "64"
}
```
I changed the items I could figure out but some of the others are not correct, like pre-link-args and data-layout.  I have no idea how they should be formatted.

**Comment by Michele31415** [comment]
And possibly of interest (I'd add this to the previous post but the Edit button doesn't work for me either):

```root@hemlock:~/mrustc1/mrustc-master/bin# ./mrustc --version
rustc 1.29.100 (mrustc v0.9.0 :)
- Build time: Monday, January 27, 2020 at  3:29:08 PM EST
- Commit:  (dirty tree)

root@hemlock:~/mrustc1/mrustc-master/bin# ./mrustc --dump-target-spec default_target.toml
Setup: V V V
Setup- operator(): sizeof(AST::TypeRef) = 344
Setup- operator(): sizeof(AST::Item) = 632
Setup- operator(): sizeof(AST::Impl) = 624
Setup- operator(): sizeof(AST::Function) = 480
Setup- operator(): sizeof(AST::Module) = 560
Setup- operator(): sizeof(HIR::TypeRef) = 176
Setup- operator(): sizeof(HIR::Path) = 104
(0.00 s) Setup: DONE
Target Load: V V V
Unknown target name ''
Abort (core dumped)
root@hemlock:~/mrustc1/mrustc-master/bin# 
```

**Comment by thepowersgang** [comment]
`./bin/mrustc --target x86_64-linux-gnu --dump-target-spec default_target.toml`

and `make -f minicargo.mk MINICARGO_FLAGS="--target ./newly_made_solaris.toml"`

**Comment by Michele31415** [comment]
I don't know what I just did but the first line worked (at least it didn't dump core):
```
root@hemlock:~/mrustc1/mrustc-master# ./bin/mrustc --target x86_64-linux-gnu --dump-target-spec default_target.toml
Setup: V V V
Setup- operator(): sizeof(AST::TypeRef) = 344
Setup- operator(): sizeof(AST::Item) = 632
Setup- operator(): sizeof(AST::Impl) = 624
Setup- operator(): sizeof(AST::Function) = 480
Setup- operator(): sizeof(AST::Module) = 560
Setup- operator(): sizeof(HIR::TypeRef) = 176
Setup- operator(): sizeof(HIR::Path) = 104
(0.00 s) Setup: DONE
Target Load: V V V
(0.00 s) Target Load: DONE
root@hemlock:~/mrustc1/mrustc-master# 
```
but I'm still not sure of what values I need in my solaris.toml file for things like 
"pre-link-args": ["-Tstm32f100.ld", "-nostartfiles"]

What I really need is a toml reference manual.  What is "-T"?  What is "stm32f100.ld"?  What does "-nostartfiles" do?  Etc.  Did I even make a .toml file?  The example in  https://github.com/toml-lang/toml
doesn't look like that.  I'm afraid I need a bit more help here.

**Comment by thepowersgang** [comment]
At a minimum, I'd try with just using the newly created `default_target.toml` (rename it to `sparcv9-sun-solaris.toml` or something), changing the obvious things to fit the target. Then see what builds.

Sadly, I don't have a solaris machine, so can't do much to help directly

**Comment by thepowersgang** [comment]
Side note: mrustc is not the only way to obtain a working rustc, you may have better luck trying to build rustc using rustc on a linux VM then copying that build to your host.

If you're wanting to use mrustc as your primary rust compiler, then expect to have a hard time - it's not very user friendly.

**Comment by Michele31415** [comment]
"At a minimum, I'd try with just using the newly created default_target.toml (rename it to sparcv9-sun-solaris.toml or something), changing the obvious things to fit the target. Then see what builds."

```
Now I can't even get it going
```
root@hemlock:~/mrustc1/mrustc-master# MINICARGO_FLAGS="--target ./sparcv9-sun-solaris.toml"
root@hemlock:~/mrustc1/mrustc-master# export MINICARGO_FLAGS
root@hemlock:~/mrustc1/mrustc-master# ./bin/mrustc --target sparcv9-sun-solaris --dump-target
Unknown option '--dump-target'
root@hemlock:~/mrustc1/mrustc-master# 
```
```
"If you're wanting to use mrustc as your primary rust compiler, then expect to have a hard time - it's not very user friendly."

So far it's easier than trying to build straight rust.  I know of no other viable option to get a rust compiler from scratch.  Mrustc was recommended to me by someone over on the rust group.

"Sadly, I don't have a solaris machine, so can't do much to help directly"

Would you like one?  I can offer you an account on my Sun T4-1.  With a 2.85 GHz. processor with 64 CPU's and 64 GB of RAM, it should be able to handle the job.

"you may have better luck trying to build rustc using rustc on a linux VM then copying that build to your host."

I do have a working rustc on a Ubuntu VM but it's x64 so it's not going to run in SPARC.  My ultimate goal is to build a recent version of Firefox and that needs rust these days.  I could cross-compile one from the Ubuntu Rust, but that looks even more complicated than building mrustc for Solaris.

**Comment by Michele31415** [comment]
I don't know what those strikeouts are doing in my code example above and I'm unable to edit them out.

**Comment by bjorn3** [comment]
> "you may have better luck trying to build rustc using rustc on a linux VM then copying that build to your host."
>
> I do have a working rustc on a Ubuntu VM but it's x64 so it's not going to run in SPARC. My ultimate goal is to build a recent version of Firefox and that needs rust these days. I could cross-compile one from the Ubuntu Rust, but that looks even more complicated than building mrustc for Solaris.

It is easy to cross-compile from x86_64 Linux to SPARC Solaris. You can do this by running `./x.py --target sparcv9-sun-solaris` inside a rust checkout on the x86_64 Linux (virtual) machine. I think the build is then located in `build/sparcv9-sun-solaris/stage2`.

**Comment by Michele31415** [comment]
"It is easy to cross-compile from x86_64 Linux to SPARC Solaris. You can do this by running ./x.py --target sparcv9-sun-solaris inside a rust checkout on the x86_64 Linux (virtual) machine. "

Wow, that would be awesome if that worked.  Unfortuately, it didn't for me.  I gave that ocmmand and it took off downloading and compiling a bunch of stuff before stopping like this:
```
michele@michele-VirtualBox:~/rust$ ./x.py --target sparcv9-sun-solaris
...
   Compiling bootstrap v0.0.0 (/home/michele/rust/src/bootstrap)
    Finished dev [unoptimized] target(s) in 2m 15s
Usage: x.py <subcommand> [options] [<paths>...]

Subcommands:
    build       Compile either the compiler or libraries
    check       Compile either the compiler or libraries, using cargo check
    clippy      Run clippy (uses rustup/cargo-installed clippy binary)
    fix         Run cargo fix
    fmt         Run rustfmt
    test        Build and run some test suites
    bench       Build and run some benchmarks
    doc         Build documentation
    clean       Clean out build directories
    dist        Build distribution artifacts
    install     Install distribution artifacts

To learn more about a subcommand, run `./x.py <subcommand> -h`

failed to run: /home/michele/rust/build/bootstrap/debug/bootstrap --target sparcv9-sun-solaris
Build completed unsuccessfully in 0:11:48
```
What am I doing wrong?

**Comment by thepowersgang** [comment]
I could probably walk you through the procedure, but I wouldn't be the best at it (and this isn't the correct forum).
If you haven't managed to solve this on your own yet, I suggest asking on the rust discord or on the forums.
