### ISSUE TITLE
Got rustup?

### ISSUE THREAD

**Issue by Michele31415** [thepowersgang/mrustc#141]
Trying to build Firefox 68 for SPARC Solaris, I have done
```
root@hemlock:~/mrustc1/mrustc-master/bin# ln -s mrustc rust
root@hemlock:~/mrustc1/mrustc-master/tools/bin# ln -s minicargo cargo
root@hemlock:~/firefox-68.0/build#  ../configure --disable-pulseaudio
...
checking for rustc... /export/home/michele/mrustc1/mrustc-master/bin/rustc
checking for cargo... /export/home/michele/mrustc1/mrustc-master/tools/bin/cargo
DEBUG: Executing: `rustup which rustc`
DEBUG: The command returned non-zero exit status 1.
DEBUG: Its error output was:
DEBUG: | Unexpected free argument
ERROR: Command `rustup which rustc` failed with exit status 1.
```

It seems to be trying to run rustup.  Does mrustc have rustup?

**Comment by thepowersgang** [comment]
There is no `rustup` in mrustc.

**Comment by Michele31415** [comment]
OK, well then I guess I can forget about trying to build Firefox for SPARC.  I guess there's a reason no one else has been able to do it.  Thanks anyway.

**Comment by thepowersgang** [comment]
Well, you could write a script that pretends to be rustup, but then you'd run into issues with mrustc+minicargo not being command-line compatible with rustc+cargo
