### ISSUE TITLE
Reducing memory usage

### ISSUE THREAD

**Issue by mid-kid** [thepowersgang/mrustc#143]
I've been messing with mrustc-0.9 to bootstrap rust-1.29.0, and most of it works fine. However, there's one step in the process while running `make -f minicargo.mk output/rustc`, where building the librustc.rlib crate generates a 758MB .c file, which in turn results in around 18GB of memory usage at its peak, and a 1.3GB .s file in /tmp.  
This makes it very unwieldy to bootstrap on my machine, and makes the whole thing rather slow, as I need to add more swap for this to build.  
This doesn't seem to be any better in the master branch.

Is there a way to lessen the strain on my memory?  
I wonder if this is the reason Guix opts to bootstrap 1.19.0 instead.

**Comment by thepowersgang** [comment]
Does 1.19.0 have noticeably better memory usage?

Memory usage, especially on the `librustc` crate is something I've noticed, and have tried to rectify (string interning, boxing of larger TU variants), but there are definitely still some improvements to be made.

**Comment by mid-kid** [comment]
Yeah, I've tried building 1.19.0 instead and the rust crate uses about 2/3rds of the memory uses by 1.29.0

**Comment by thepowersgang** [comment]
well, since 1.29.0's librustc is about 50% bigger, that would make sense (3.2MB vs 4.6MB)

I'm doing some analysis to see what's using that memory, and where memory can be saved - but it'll take a while.

**Comment by thepowersgang** [comment]
The experimental `true_typeref` branch has significantly improved memory usage, but is still being debugged.
This may come at a slight performance hit, still to be determined (and improved).

**Comment by thepowersgang** [comment]
Testing the above branch on my (64-bit) linux box shows 1.7G `mrustc` and 9.5G `cc1`, a definite improvement.

**Comment by mid-kid** [comment]
Disk usage is about the same as it used to be, but memory usage has been reduced to about 8GB at its peak. Thanks a lot!
The performance hit on my machine is greatly reduced by not having to swap nearly as much, so I don't know if it's significantly slower on devices with enough memory.

Disk usage wasn't the point of this issue, but to reduce it dramatically you can apply these `sed` lines to build without the debug info:
```
sed -i -e 's/CMAKE_BUILD_TYPE=RelWithDebInfo/CMAKE_BUILD_TYPE=Release/' \
    minicargo.mk
sed -i -e 's/ -g\>//' Makefile tools/common/Makefile tools/minicargo/Makefile
sed -i -e '/args.push_back("-g");/d' tools/minicargo/build.cpp
```
This makes a 90M `mrustc`, and saves a good 25+GB during build.

**Comment by thepowersgang** [comment]
The `true_typeref` branch has now been merged with master. There's probably some more RAM gains to be had, but the bulk of the work is done.
