### ISSUE TITLE
Error when using no_core and no_std attributes at the same time

### ISSUE THREAD

**Issue by aristarh2704** [thepowersgang/mrustc#145]
If I use no_core and no_std attributes at the same time, mrustc say:
`Invalid use of #![no_std] with itself or #![no_core`
But rustc print nothing in this situation.

**Comment by bjorn3** [comment]
`#![no_core]` is `#![no_std]` without implicitly importing `core`. I am surprised that rustc doesn't give an error when using them both.

**Comment by thepowersgang** [comment]
Does this block compiling wild rust code (e.g. from crates.io, or just some random package?)

I'm also surprised that rustc doesn't also emit an error (or at least a warning) if both are provided.

**Comment by bjorn3** [comment]
Filled rust-lang/rust#73096
