### ISSUE TITLE
Usable for exotic embedded targets?

### ISSUE THREAD

**Issue by cody82** [thepowersgang/mrustc#162]
Can this be used for embedded/no_std targets like Tricore or PowerPC where only a C compiler exists?
My plan is to implement some functions in Rust, compile them to C with mrustc and use them from normal C code which is compiled by a proprietary C compiler.
Is this possible or are there major problems with that approach?

**Comment by bjorn3** [comment]
tl;dr: you need to try it

longer answer: Mrustc implements what is necessary to bootstrap rustc. Other crates may or may not work. In any case things like borrowck that are not necessary to bootstrap rustc are not implemented. The only way to know for sure if something will work is by trying it. PowerPC is already supported by LLVM and rustc by the way.

**Comment by cody82** [comment]
Thanks!
Last time I checked I only saw Linux on PowerPC as a target. Not bare metal without OS.

**Comment by cody82** [comment]
I did not know, thank you again!
