### ISSUE TITLE
Does mrustc work with multiple mutable borrows?

### ISSUE THREAD

**Issue by Ekuju** [thepowersgang/mrustc#164]
I wasn't able to get this building on my mac, possibly due to some weird setup I have going on. So I wasn't able to test it myself, but I have a question regarding this project.

> `mrustc` works by compiling assumed-valid rust code (i.e. without borrow checking) into a high-level assembly (currently using C, but LLVM/cretonne or even direct machine code could work) and getting an external code generator to turn that into optimised machine code. This works because the borrow checker doesn't have any impact on the generated code, just in checking that the code would be valid.

> This works because the borrow checker ... just checks that the code would be valid.

This implies to me that invalid rust code such as this example below won't work with mrustc despite the lack of borrow checking.
```
fn main() {
    let mut a = 1;
    let b = &mut a;
    let c = &mut a;
    
    *b += 1;
    *c *= 2;
    
    println!("a {:?}", a);
}
```

But my understanding (that might be incorrect) is that the borrow checker is only there to ensure the high level rust-specific borrow rules aren't broken. Does the borrow checker validation have any implication regarding the actual legitimacy of the code itself? Would the above example work in mrustc in the same way that similar type of thing would work in C++?

The ability to turn off the borrow checker seems like a really appealing idea for certain types of applications, such as game development for example.

**Comment by thepowersgang** [comment]
That code would compile with mrustc, but may mis-compile due to assumptions made in the optimiser. (Which still assumes that `&mut` is unique).

mrustc''s lack of a borrow checker is a limitation, not a design decision (adding one has been on my todo list for a while, since it would catch some mis-compilation errors before reaching codegen).

**Comment by Ekuju** [comment]
Thanks for the info, I wasn't sure if there were any optimizations based on this idea. Do you know where that optimization might be happening? I would think it would be before and transpiling/compiling since &mut being unique is a rust specific optimization.

And as a follow up question, do you know where that optimization might be happening in the actual rust compiler? Not sure if you're familiar with that code base. I might try to remove that optimization and the borrow checker to make rust more suitable for game development (for my own purposes.)

**Comment by thepowersgang** [comment]
In mrustc, the optimisations are in `mir/optimise.cpp`... in rustc, no idea.

My suggestion is to accept that `&mut` means 'unique' and instead use `Cell` and other interior-mutable types with controlled mutation.

**Comment by Ekuju** [comment]
> My suggestion is to accept that &mut means 'unique' and instead use Cell and other interior-mutable types with controlled mutation.

Yeah unfortunately this is what I have been doing. It still makes the code much harder to work with than cpp. The conclusion I've come to is that, although I enjoy writing rust code much more than cpp in almost every aspect, for game development it's relatively unusable due to the borrow checker. Especially when you have complex systems between entities, components, and entities/components.

A lot of the data structure type things you'd typically want to do as good practice in games are somewhat similar to linked lists or trees that you can bidirectionally traverse up and down. Both of these rust historically struggles with a bit, needing to have unsafe wrappers. :(

Thanks for the help though, very informative. I think I'm going to spend at least a few days messing with rustc to see if I can unborrow-check everything. Do you think mrustc is mature enough to be able to compile some syntactically simple projects? It seems like it would be much easier to spin off from mrustc but I worry about using an unfinished compiler in a professional project.

I'll go ahead and close this task out though, thanks again.

**Comment by bjorn3** [comment]
If you don't want to use the borrow checker, you can use raw pointers everywhere.

> Especially when you have complex systems between entities, components, and entities/components.

It is by the way perfectly possible to use an ECS without unsafe code. Have you seen for example Bevy?

> A lot of the data structure type things you'd typically want to do as good practice in games are somewhat similar to linked lists or trees that you can bidirectionally traverse up and down. Both of these rust historically struggles with a bit, needing to have unsafe wrappers. :(

Why is that? Linked lists are generally terrible for cache usage due to low data locality.

**Comment by Ekuju** [comment]
I've seen bevy but I didn't know it had no unsafe code, that's impressive. I've been using hecs for a project lately, which does have unsafe access. There are methods to access components by type, mutable components by type, and mutable components by type with unique access to each entity.

The difference between the last 2 is that mutable components by type is safe for the entire archetype, i.e. one mutable component access per the same entity "definition". The unsafe method is safe per entity, one mutable component access per entity which is the behavior you would expect by default.

However for I'd like to be able to chain entities for example, basically a scene graph of data. Components can be contiguous memory as owned by the system, but chaining entities makes it conceptually easy to attach things like weapons, have different parts of the world itself moving without affecting the entities inside of it, etc.

With this design you're now in a situation where when you update an entity you may need to reference upward and modify some parent data.

And ultimately anyways, I'd argue that the rust borrow checker doesn't really make game code safer. It's either undefined behavior or crash, at least for most cases.

**Comment by bjorn3** [comment]
> I've seen bevy but I didn't know it had no unsafe code, that's impressive.

It does, but none of it is visible to the user of Bevy. That is the whole premise of Rust. It is simply impossible to avoid unsafe code for anything non-trivial. The trick is encapsulating the unsafe code with a safe api.
