### ISSUE TITLE
usize constant handling assumes 64-bit width

### ISSUE THREAD

**Issue by hvdijk** [thepowersgang/mrustc#168]
pub fn test() -> bool {
      let a: usize = 0x0000FFFF;
      let b: usize = 0xFFFF0000;
      a == !b
    }

When compiling with `bin/mrustc --target i586-linux-gnu --crate-type rlib test.rs -L output`, this results in

    // ::"test"::test
    bool  ZRG1c4test4test0g(void)
    {
    	bool rv;
    	rv = false;	// retval = Constant(false)
    	return rv;
    	// ^ Return
    }

For 32-bit targets, this should return true.

There are a few places where `::HIR::CoreType::Usize` is handled the same way as `::HIR::CoreType::U64`, where it should be handled as either `::HIR::CoreType::U64` or `::HIR::CoreType::U32` depending on the target, and likewise for `::HIR::CoreType::Isize`.

**Comment by thepowersgang** [comment]
This should be fixed completely with the new full MIRI constant evaluator.

**Comment by thepowersgang** [comment]
(It's not fixed)

**Comment by thepowersgang** [comment]
Correction - was testing on a 64-bit machine. Confirmed fixed.
