### ISSUE TITLE
Compiling llvm with multiple jobs

### ISSUE THREAD

**Issue by est31** [thepowersgang/mrustc#17]
I was doing `make output/rustc -j 8` to compile rustc. Then I saw that when building LLVM, only one core was utilized, even though I have 7 more.

**Comment by thepowersgang** [comment]
set `LLVM_PAR_LEVEL="-j 8"` - make doesn't pass -j down to sub-instances it seems

**Comment by est31** [comment]
Hmm, I think I'll file a PR.
