### ISSUE TITLE
Fuzz test against rustc

### ISSUE THREAD

**Issue by DemiMarie** [thepowersgang/mrustc#171]
This is a long shot and I have absolutely no expectation that it will be implemented, but it _is_ a cool idea, if nothing else.  Feel free to close it if you don’t think it would be a good use of time.

The idea is to fuzz-test `mrustc` against `rustc`.  If `mrustc` rejects a program `rustc` accepts, or if they produce different outputs for the same code, either one of them is buggy or the source program has UB.  But safe Rust cannot have UB, so as long as all of the fuzz inputs do not use `unsafe`, all such differences will be bugs.

**Comment by dtolnay** [comment]
> if they produce different outputs for the same code, either one of them is buggy or the source program has UB. But safe Rust cannot have UB, so as long as all of the fuzz inputs do not use `unsafe`, all such differences will be bugs.

It is not an accurate conclusion that absence of UB implies totally reproducible behavior across different toolchains, or even across consecutive invocations of mrustc or rustc. Example: random number generators. Or simpler: it would be extremely unusual for the following program to print the same number across different toolchains:

```rust
fn main() {
    println!("{}", main as usize);
}
```

**Comment by ian-fox** [comment]
It may be possible to compare them without needing the binaries to be bit-for-bit identical. `main` may have a different address, but if one compiler builds the program successfully and the other one raises an error that would be an indication of a problem.

It may be possible to do some more advanced analysis than that too, but I'd have to think about it.

**Comment by DemiMarie** [comment]
> It may be possible to compare them without needing the binaries to be bit-for-bit identical. `main` may have a different address, but if one compiler builds the program successfully and the other one raises an error that would be an indication of a problem.
> 
> It may be possible to do some more advanced analysis than that too, but I'd have to think about it.

I believe that if we ban converting pointers to integers, the results (for safe Rust) should be deterministic in a significant fraction of cases.

**Comment by thepowersgang** [comment]
A potentially interesting way of finding compiler crashes, but definitely not something for the near/medium future (where correctness is the goal - which isn't really something fuzzable, see the `main as usize` above).
Closing mostly to keep the issue list clear.
