### ISSUE TITLE
Does not compile with GCC 11

### ISSUE THREAD

**Issue by JustAnotherStrange** [thepowersgang/mrustc#177]
Trying to build: mrustc with the minicargo.mk makefile
Host System: EndeavourOS Linux (Arch-based, uses Arch repos)
Compiler Versions: gcc 11.1.0
Version of repo: just a plain `git clone https://github.com/thepowersgang/mrustc.git` and nothing else, on latest commit

![image](https://user-images.githubusercontent.com/64844168/118875024-913bad80-b8b9-11eb-9cc7-e967e9f0d6cd.png)

I run this command, and wait a bit over a minute, and everything seems to be going normally, and then this error shows
![image](https://user-images.githubusercontent.com/64844168/118875149-b29c9980-b8b9-11eb-8cf6-5a08c099ac1a.png)

It keeps going for 15 or so more seconds, and then it exits with status 2
![image](https://user-images.githubusercontent.com/64844168/118875302-e24ba180-b8b9-11eb-9fa4-7f678cd2858b.png)

**Comment by nabijaczleweli** [comment]
Try adding `#include <limits>` to the head of `codegen_c.cpp` maybe?

**Comment by JustAnotherStrange** [comment]
Fixed it! Compiled. Thanks. Should this be closed now?

**Comment by nabijaczleweli** [comment]
Preferably you'd open a PR with that first, or let the maintainer push it, considering the triviality.
