### ISSUE TITLE
  - x86-64 linux (fully bootstrap tested)   

### ISSUE THREAD

**Issue by lulcat** [thepowersgang/mrustc#180]
- x86-64 linux (fully bootstrap tested)
  
Well no. it fails to bootstrap 1.39.0 on x86-64 musl. I am in desperation using the rustup binary in hope to get a rust. 

But since as a principle all binaries should be bootstrapped in a distro, I am returning to this, will see if I can figure it out.

**Comment by thepowersgang** [comment]
You are correct, the "x86-64 linux" refers to the standard GNU standard library. I will update the readme with more specifics of where it's tested.
