### ISSUE TITLE
Is the toml file enough for adding new targets?

### ISSUE THREAD

**Issue by cesss** [thepowersgang/mrustc#182]
One of the things that is stopping me from adopting Rust is the lack of support it has for a number of machines I still use. Even if I can use the official Rust compiler in my everyday machines, I wish to be able to at least build my code in the other machines as well (for example: PowerPC Macs, and x86 Snow Leopard Macs, both of them unable to run the official Rust compiler). Additionally, I'd like to be able to build my code in other historical machines if I need so.

If the target can build C11 code and the C runtime library is reasonably standard, should it be enough to write a toml file for getting that target supported?

Is there any list of the C runtime library functions that the generated C11 code can call? (this question is important in order to see whether a given target can be easily supported or not)

**Comment by thepowersgang** [comment]
Creating a target description toml file is enough to get mrustc to (try to) emit code. BUT, you'll still need rust standard library support.

**Comment by cesss** [comment]
Thanks a lot. After taking a look at Rust this week, I decided I'm not adopting it. I probably would if the complete implementation was written on top of C and on top of the standard C library, because I really value extreme compatibility. So, I stick to C 😄
