### ISSUE TITLE
Building core fails (rustc 1.39.0)

### ISSUE THREAD

**Issue by concatime** [thepowersgang/mrustc#188]
Hi,
maybe I’m doing something wrong, maybe not.. but I get `:0: error:0:Undefined language item 'non_zero' required` when `mrustc` and `minicargo` try to build crate `core`.
[Here](https://gitlab.com/iemaghni/mrustc-alpine/-/jobs/1582336339#L451) are the full logs (error at line 451). You can see at line 63 that the commit hash is `01f73e7894119405ab3f92b6191f044e491c9062`, aka the latest in branch master.
To ease the debug, I built a GitLab CI at this repo: https://gitlab.com/iemaghni/mrustc-alpine.
Feel free to fork and play with it. You can also spin an Alpine VM on your machine and copy commands from `.gitlab-ci.yaml`.
Issam.

**Comment by concatime** [comment]
Same error on Ubuntu: https://gitlab.com/iemaghni/mrustc-ubuntu/-/jobs/1582390368#L881

**Comment by thepowersgang** [comment]
That error likely means that you're building 1.39 without setting `MRUSTC_TARGET_VER=1.39`.
See the `build-1.39.0.sh `script

**Comment by concatime** [comment]
You’right, thank you!
