### ISSUE TITLE
Bootstrapping of rustc stage0 on unsupported platforms?

### ISSUE THREAD

**Issue by jirutka** [thepowersgang/mrustc#2]
I wonder, is this project already capable of bootstrapping rustc on platforms for which there's no binary snapshot?

My use case is to build Rust on x86_64 with musl libc.

**Comment by thepowersgang** [comment]
Not yet :) I'm still working on the first pass of getting it to compile libcore.

Hopefully once it's "complete" then you could bootstrap rustc anywhere there's a functioning C++ compiler.

**Comment by jirutka** [comment]
Thanks for the response. When do you expect that it will be complete - is it a matter of weeks, months, years...?

**Comment by thepowersgang** [comment]
Several months at best estimate.

**Comment by jirutka** [comment]
I see that you're still hard working on it and have done pretty impressive progress! I'd like to ask, how far are you now from being able to compile rustc with mrust?

BTW does Rust's developers know about this heroic effort and support you?

**Comment by thepowersgang** [comment]
Hard to know how far - There's no real code generation, and with every new crate I hit more snags. BUT - all dependencies to libstd "compile", and libstd is almost past expansion.

Most of the rust core team know about it - I've been asking questions on IRC for months (clarifying behaviours and complaining about quirks)

**Comment by DemiMarie** [comment]
@thepowersgang What can mrustc compile so far?

**Comment by thepowersgang** [comment]
The README lists most of the progress, but sometimes things go backwards (as new features are introduced with various bugs).

Most of rustc compiles, and a large chunk of the run-pass tests compile and pass.

**Comment by jrmuizel** [comment]
It looks like rustc sort of runs now. However, I get a:
 error[E0463]: can't find crate for `std`
when compiling a hello world with the new compiler.

**Comment by thepowersgang** [comment]
Yes, the generated rustc will "run", but cannot compile anything (attempting to compile libcore ends with a segfault on my local build, and `unreachable code` in current git)

**Comment by thepowersgang** [comment]
Update - The script TestRustcBootstrap.sh in the repository root can be used to build a working rustc from scratch, and compare it with the normal bootstrap process.

**Comment by aclemons** [comment]
Should this be working now? I am trying to bootstrap rustc with gcc 5.5.0 and it is failing to build. (Revision 8e00201)

```
$ make -j1 -f minicargo.mk # SUCCESS
$ make -j1 -C run_rustc # FAILURE
make: Entering directory '/tmp/aclemons/mrustc-8e002015416954fa5e9444c9d81ec7f4b291562f/run_rustc'
[RUSTC] -o prefix/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcore.rlib
Command terminated by signal 6
20.33user 0.23system 0:20.57elapsed 99%CPU (0avgtext+0avgdata 1822304maxresident)k
0inputs+0outputs (0major+105405minor)pagefaults 0swaps
Makefile:37: recipe for target 'prefix/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcore.rlib' failed
make: *** [prefix/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcore.rlib] Error 6
make: Leaving directory '/tmp/aclemons/mrustc-8e002015416954fa5e9444c9d81ec7f4b291562f/run_rustc'
```

Manually running the command:

```
$ ../output/rustc -Vv
rustc 1.19.0-stable-mrustc
binary: rustc
commit-hash: unknown
commit-date: unknown
host: x86_64-unknown-linux-gnu
release: LLVM version: 4.0
$ ../output/rustc  -L prefix/lib/rustlib/x86_64-unknown-linux-gnu/lib/ -L ../output/libs ../rustc-1.19.0-src/src/libcore/lib.rs -o prefix/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcore.rlib
Aborted
```

Happy to provide more info if needed.

**Comment by thepowersgang** [comment]
Try with GCC 6... this may be a bug in GCC itself (or some edge case UB being triggered by the mrustc generated code).

**Comment by davidsullins** [comment]
For what it's worth, I saw the same issue as @aclemons using gcc 5.3.0 and commit cec5b32

**Comment by thepowersgang** [comment]
Issue #63, I've seen it on Mint 18 (which uses 5.5.0), but not on my custom-built GCC 6 on Debian

**Comment by aclemons** [comment]
Thanks. I've just tested with Slackware-current which has gcc 7.3.0 and can confirm that it builds successfully there. (I was trying before with Slackware 14.2/stable which has gcc 5.5.0). I'll watch #63 for updates.

**Comment by thepowersgang** [comment]
Closing. mrustc should be able to compile rustc on anything supported by libstd (and llvm).
