### ISSUE TITLE
@test_cmd.txt: No such file or directory

### ISSUE THREAD

**Issue by evanmiller** [thepowersgang/mrustc#205]
Finally have `mrustc` and standard libraries compiling on Mac OS X 10.6, but I'm having trouble compiling a "Hello, world!". From the code directory, I'm trying:

```
$ env MRUSTC_TARGET_VER=1.39 ./bin/mrustc -L output-1.39.0 ~/test.rs
...
Trans Enumerate: V V V
(0.00 s) Trans Enumerate: DONE
Trans Auto Impls: V V V
(0.00 s) Trans Auto Impls: DONE
Trans Monomorph: V V V
(0.00 s) Trans Monomorph: DONE
MIR Optimise Inline: V V V
(0.00 s) MIR Optimise Inline: DONE
Trans Enumerate Cleanup: V V V
(0.00 s) Trans Enumerate Cleanup: DONE
Trans Codegen: V V V
Running command - "gcc" @"test_cmd.txt"
i686-apple-darwin10-gcc-4.2.1: @test_cmd.txt: No such file or directory
i686-apple-darwin10-gcc-4.2.1: no input files
C Compiler failed to execute - error code 256
```

Any ideas on this one?

**Comment by bjorn3** [comment]
Does

```
$ echo "int main(void) { return 0; }" > foo.c
$ echo "foo.c -o foo" > args.txt
$ gcc @args.txt
```

give an error? If it does, your gcc version is probably too old to have response file support.

**Comment by evanmiller** [comment]
@bjorn3 It does not give an error and response files appear to compile just fine.

**Comment by evanmiller** [comment]
You know, I'm wondering if it's really a permissions problem (e.g. writing out `@test_cmd.txt`). Will test that theory once this recompile finishes.

**Comment by thepowersgang** [comment]
Probably the case. `std::ofstream` doesn't have good error reporting, so it's probable that the write silently failed.

**Comment by evanmiller** [comment]
Yep, it compiles once I have permission on `$PWD`. So I guess the request here would be for a better error message or an earlier failure.

**Comment by thepowersgang** [comment]
An error message is on its way.
