### ISSUE TITLE
Support `--version` and `--verbose` flags in minicargo

### ISSUE THREAD

**Issue by evanmiller** [thepowersgang/mrustc#207]
I'd like to use mrustc / minicargo to compile the Rusty bits of SpiderMonkey (aka mozjs). One of the immediate issues is that the configure system is not happy with minicargo. It would be great if the output of `minicargo --version` and `minicargo --version --verbose` imitated that of standard Cargo.

```
$ cargo --version
cargo 1.57.0
$ cargo --version --verbose
cargo 1.57.0
release: 1.57.0
host: aarch64-apple-darwin
libgit2: 1.3.0 (sys:0.13.25 system)
libcurl: 7.80.0 (sys:0.4.51+curl-7.80.0 system ssl:OpenSSL/3.0.1)
os: Mac OS 12.1.0 [64-bit]
```

(For configuration purposes I think just the `cargo` and `release:` lines would be sufficient)

**Comment by thepowersgang** [comment]
Unlike `mrustc`, `minicargo` doesn't present a similar interface to `cargo` (the command-line interface is very different).
A better solution would be a shim that translates `cargo`'s CLI into `minicargo`'s
