### ISSUE TITLE
Support use as a Rust->C transpiler

### ISSUE THREAD

**Issue by emosenkis** [thepowersgang/mrustc#21]
I'm interested in using mrustc to allow me to write code in Rust for a platform not supported by LLVM (ESP8266), then transpile it to C and call it from a shim written in C/C++. I tried using mrustc on a trivial library and discovered that, even with #[no_mangle], the resulting C function did not retain its original Rust name.

Other features that would be helpful for this include an option to produce C output without compiling it and an option to use regular rustc to produce MIR and then transpile that to C.

I haven't tried using mrustc on Rust code that calls out to a C or C++ library, but if that's not supported already, it would be critical to my use case (e.g. writing Rust code on top of the ESP8266 Arduino library).

Thanks for your work on this project so far!

**Comment by thepowersgang** [comment]
1. #[no_mangle] should work (it will create a `#define` alias, or a symbol alias to the actual name)
1. Emitting C without compiling it is a usecase I have been thinking of (to avoid the long compile times seen with some crates)
1. Using rustc's MIR is not exactly feasible, as it is subtly different to the mrustc MIR.
1. Calling out to C code is implemented (and is required for building a usable libstd), so it's good there :)

**Comment by emosenkis** [comment]
Great! Now that I'm looking, I see the `#define` alias. I see it also works great with `#![no_std]`. Now I can go straight to trying to put together a complete build script for compiling an ESP8266 Arduino-based firmware written in Rust. I'll try to do some sort of blog post if I succeed.

**Comment by lschuermann** [comment]
This is exactly my use case! I would just want to implement some simple algorithms using Rust and then use the resulting C-code on various microcontrollers which only have gcc support.

@emosenkis Is this working for you? Which steps to you need to do?
@thepowersgang Would it be possible to add an example to the `README`, on how to build a very simple hello world example program with `mrustc`? I'm very much lost and can't seem to get it to work.

**Comment by emosenkis** [comment]
https://github.com/emosenkis/esp-rs that is
