### ISSUE TITLE
Error building libc v0.2.62 (`Expecting OpenNamed(St6vector...)`)

### ISSUE THREAD

**Issue by evanmiller** [thepowersgang/mrustc#213]
This occurs with HEAD and after building with GCC 11

```
bin/mrustc rustc-1.39.0-src/vendor/libc/src/lib.rs -o output-1.39.0/liblibc-0_2_62_Hd.rlib --crate-name libc --crate-type rlib -C emit-depfile=output-1.39.0/liblibc-0_2_62_Hd.rlib.d --crate-tag 0_2_62_Hd -g --cfg debug_assertions -O -L output-1.39.0 --cfg libc_priv_mod_use --cfg libc_union --cfg libc_const_size_of --cfg libc_align --cfg libc_core_cvoid --cfg libc_packedN --cfg libc_thread_local --cfg feature="rustc-dep-of-std" --cfg feature="align" --cfg feature="rustc-std-workspace-core" --extern rustc_std_workspace_core=output-1.39.0/librustc_std_workspace_core-1_99_0.rlib
 Expecting OpenNamed(St6vectorIN3HIR12TypeParamDefESaIS1_EE), got OpenNamed(NSt3__16vectorIN3HIR12TypeParamDefENS_9allocatorIS2_EEEE)
Process was terminated with signal 6
```

**Comment by thepowersgang** [comment]
Probably stale object files, this shouldn't happen but sometimes does. Make sure you're using a fully clean output directory.

**Comment by evanmiller** [comment]
The error occurs in a clean directory (fresh extract etc).

**Comment by thepowersgang** [comment]
Are you sure your build is completely clean?
The two types appear to be different implementations of `std::vector<HIR::TypeParamDef>`
- `std::vector<HIR::TypeParamDef, std::allocator<HIR::TypeParamDef> >` (`St6vectorIN3HIR12TypeParamDefESaIS1_EE`)
- `std::__1::vector<HIR::TypeParamDef, std::__1::allocator<HIR::TypeParamDef> >` (`NSt3__16vectorIN3HIR12TypeParamDefENS_9allocatorIS2_EEEE`)

**Comment by evanmiller** [comment]
Now that I look further into it, it's possible that this and #210 are due to dirty builds. I have patched the binary to use a default value of `MRUSTC_LIBDIR`, which is pointing to an installed (older) directory. I will clean things up on this end and see if things start working better.
