### ISSUE TITLE
Initial `make` `ar` warning message for `common_lib.a`

### ISSUE THREAD

**Issue by rlee287** [thepowersgang/mrustc#215]
When initially running `make` on Linux (Ubuntu 20.04.3), the line `[AR] rcu ../../bin/common_lib.a` produces the warning `ar: 'u' modifier ignored since 'D' is the default (see 'U')`. Does the `ar` invocation for this library need to be adjusted?

**Comment by thepowersgang** [comment]
Not sure about it needing to be changed.
For some reason (not sure why) my default is to use "update" mode in `ar` - but that message is saying that it defaults to deterministic mode (which makes update not work).
I'd force non-deterministic mode, but that wouldn't work with `llvm-ar` (used by OSX)

For now, not a real issue but I'll see about tweaking the option list so it makes everything happy.

**Comment by thepowersgang** [comment]
Should be fixed with 3924a6871f5039ca1d00aaa76459cbd100b8e5ff

**Comment by rlee287** [comment]
I'm no longer seeing that warning, so it's fixed for me. Closing for now, but anyone else who sees similar warnings from `ar` on a slightly different *nix sysem can comment here if they still encounter them.
