### ISSUE TITLE
Implement derive on unions

### ISSUE THREAD

**Issue by emosenkis** [thepowersgang/mrustc#22]
In trying to build a simple ESP8266 firmware example, I am unable to compile my crate of [generated bindings](https://github.com/emosenkis/arduino-esp-rs) to the Arduino library because it depends on deriving Copy on unions:

```
:0: BUG:src/expand/derive.cpp:2186: TODO: handle - Handle #[derive] for other item types - Union
```

**Comment by thepowersgang** [comment]
(I was bored/procrastinating, and rustc progress is stuck on a typecheck issue - this was easy to fix)

**Comment by emosenkis** [comment]
Thanks! That did the trick. I now have a working blink firmware for ESP8266 written in Rust! I had to delete the 128-bit integer typedefs and functions (ESP8266 is 32-bit). Is there a way to tell mrustc that my target is 32-bit?

**Comment by thepowersgang** [comment]
add a 32-bit target to src/trans/target.cpp
