### ISSUE TITLE
Can't compile trivial program with `mrustc` on macOS

### ISSUE THREAD

**Issue by catap** [thepowersgang/mrustc#228]
Local root: https://github.com/catap/mrustc/tree/rust-1.54.0-macos

A program:
```rust
fn main() {
    println!("Hello World!");
}
```

an attempt to compile it fails as:
```
> ./bin/mrustc -L $(pwd)/output-1.54.0 hello.rs
Setup: V V V
(0.00 s) Setup: DONE
Target Load: V V V
(0.00 s) Target Load: DONE
Parse: V V V
(0.00 s) Parse: DONE
LoadCrates: V V V
(0.32 s) LoadCrates: DONE
Expand: V V V
(0.00 s) Expand: DONE
- main: params.outfile = hello
Implicit Crates: V V V
:0: error:0:Unable to locate crate 'alloc_system' in search directories
```

I've bootstraped `mrustc` as:
```
env RUSTC_VERSION=1.54.0 MRUSTC_TARGET_VER=1.54 OUTDIR_SUF=-1.54.0 make -f minicargo.mk LIBS output-1.54.0/rustc
```

What is puzzling me: I have the only one file which contains `alloc_system`:
```
> find . -type f -iname '*alloc[_-]system*'
./rustc-1.54.0-src/compiler/rustc_codegen_cranelift/example/alloc_system.rs
```

**Comment by bjorn3** [comment]
Rustc 1.54 no longer uses `alloc_system` (it got merged into libstd)

I think `TARGETVER_LEAST_1_39` is false at https://github.com/thepowersgang/mrustc/blob/f548f8d7a36e7344ca5442bd5c21d39667035aa9/src/main.cpp#L465-L473 for some reason.

**Comment by evanmiller** [comment]
Try

```
env MRUSTC_TARGET_VER=1.54 ./bin/mrustc -L $(pwd)/output-1.54.0 hello.rs
```

Without this variable set, `gTargetVersion` defaults to 1.29. (Note that one of the MacPorts patches overrides this default, so with MP `mrustc`, manually setting `MRUSTC_TARGET_VER` is unnecessary.)

**Comment by catap** [comment]
@evanmiller indeed!

Let me close then an issue.
