### ISSUE TITLE
Assertion failed: (t == ":"), function load_depfile, file build.cpp, line 817

### ISSUE THREAD

**Issue by evanmiller** [thepowersgang/mrustc#251]
The MacPorts build bots are all green except on OS X 10.7:

```
(0/8) BUILDING cfg_if from cfg-if v0.1.10
> /opt/local/var/macports/build/_opt_bblocal_var_buildworker_ports_build_ports_lang_mrustc/mrustc/work/mrustc-15a5cb1f066bd148bd2959c63adb649e7a06e5ce/bin/mrustc rustc-1.54.0-src/vendor/cfg-if-0.1.10/src/lib.rs -o output-1.54.0/libcfg_if-0_1_10.rlib --crate-name cfg_if --crate-type rlib -C emit-depfile=output-1.54.0/libcfg_if-0_1_10.rlib.d --crate-tag 0_1_10 -g --cfg debug_assertions -O -L output-1.54.0 --edition 2018
Assertion failed: (t == ":"), function load_depfile, file build.cpp, line 817.
make: *** [output-1.54.0/libpanic_unwind.rlib] Abort trap: 6
```

https://build.macports.org/builders/ports-10.7_x86_64-builder/builds/89034/steps/install-port/logs/stdio

Any ideas spring to mind?

**Comment by thepowersgang** [comment]
Not seen that before - that code is while parsing the dependency files, I'd guess something is malformed in one of them (not sure which, probably one of the standard library crates)

**Comment by catap** [comment]
@thepowersgang I do have macOS 10.7 virtual machine, I'll try to reproduce it ;)

**Comment by thepowersgang** [comment]
Probably caused by a full disk. Leaving this open as a reminder to improve error reporting in that function
