### ISSUE TITLE
Questions regarding this project

### ISSUE THREAD

**Issue by Raj2032** [thepowersgang/mrustc#261]
Hi I have some questions regarding this project:

1. Am I able to disable all safeties such as bounds checking, utf8 checks etc as it has overhead? They are useful for debugging but for production release, especially for video games where performance vs security is favored, I would prefer to disable such safety checks, is this possible with `mrustc`?
2. Can I compile a large project that was working fine with the original `rustc` compiler with `mrustc`, or am I expecting build issues at this time?
3. Would `mrustc` generate less performant code compared to `rustc`?

**Comment by bjorn3** [comment]
1. If your game is multiplayer you better make sure you keep safety features like bound vhecks enabled. In any case when using iterators you don't get bound checks anyway.
2. It will depend on the exact project. Mrustc only implements the subset of rust necessary to bootstrap rustc. Even if you stay within this subset you may hit edge cases where type inference is slightly different.
3. Building with mrustc is about 1.5x slower than with rustc: https://old.reddit.com/r/rust/comments/7lu6di/mrustc_alternate_rust_compiler_in_c_now_broken/drp2h5q/. I don't know how the runtime performance compares.

**Comment by thepowersgang** [comment]
1. `mrustc` has no inbuilt borrow checks (yet), but does rely on the borrow rules for optimisations to be correct. Indexing and overflow checks aren't present (well, slice ones aren't), but the same caveat applies. You _don't_ want to break these assumptions (or UB happens)
2. If it built with 1.54, then it should build with `mrustc` (but that doesn't mean it will - just that it should).
3. `mrustc`'s generated code is VERY bad, much worse than rustc's

**Comment by Raj2032** [comment]
I see thanks guys
