### ISSUE TITLE
Unknown Macro while compiling 1.54.0

### ISSUE THREAD

**Issue by emckee2006** [thepowersgang/mrustc#263]
mrustc rustc-1.54.0-src/library/core/src/lib.rs -o output/libcore.rlib --crate-name core --crate-type rlib -C emit-depfile=output/libcore.rlib.d --crate-tag 0_0_0 -g --cfg debug_assertions -O -L output --edition 2018
:0: error:0:Unknown macro {}panic/*?*/
rustc-1.54.0-src/library/core/src/num/f32.rs:1015: note: From here
Process was terminated with signal 6

**Comment by thepowersgang** [comment]
How are you running it?
`mrustc` uses environment variables to control the target version. That error seems like that isn't set correctly for 1.54

Try with `MRUSTC_TARGET_VER=1.54` (or use the `build-1.54.0.sh` script)

**Comment by emckee2006** [comment]
I had put 1.54.0 in the version file... I'll try it as a variable
