### ISSUE TITLE
Allow to turn off -g during builds

### ISSUE THREAD

**Issue by Vogtinator** [thepowersgang/mrustc#264]
Currently minicargo defaults to pass `-g` to every `mrustc` invocation, which makes the built object files absolutely enormous. During `rustc_main` linking this leads to a lot of space and time being consumed. Simply by removing the `-g` flag I could speed up `rustc` building by multiple orders of magnitude. I'm not exaggerating - it went from multiple minutes per crate to below a second!

**Comment by thepowersgang** [comment]
Making `-g` optional has been on the TODO list for a while (it's useful when debugging codegen failures).
Didn't realise it would be that big a difference.

**Comment by thepowersgang** [comment]
Welp, that worked, and was pretty quick. Good spot.
(Now I have to re-build with debug enabled, because debugging a codegen error)

**Comment by Vogtinator** [comment]
There's still a place left where it passes `-g` unconditionally: https://github.com/thepowersgang/mrustc/blob/e2cf30110452c872f403bd358daf83b4a1687527/tools/minicargo/build.cpp#L1113

**Comment by thepowersgang** [comment]
Eh, that's just the build script.
