### ISSUE TITLE
Incorrect operations after casting

### ISSUE THREAD

**Issue by lukyxu** [thepowersgang/mrustc#270]
```
fn main() {
  let a = 545201568421088164_isize as i32;
  let b = a / 30313;
  println!("{} {}", a, b);
}
```

Expected output:
414813092 13684

Actual Output
414813092 -1588584387

**Comment by thepowersgang** [comment]
Looks like a problem in MIR constant propagation, it isn't properly truncating when propagating through casts.
Working on a fix

**Comment by lukyxu** [comment]
Thanks, the fix seems to work.

**Comment by lukyxu** [comment]
Not sure if this is related but:

```
fn main() {
  let a = 14691741563521255844 / -5797230713929758116_isize as usize;
  println !("{}", a)
}
``` 

Expected output:
1

Actual output:
-2
