### ISSUE TITLE
Incorrect wrapping_mul/wrapping_div operations on negative overflow

### ISSUE THREAD

**Issue by lukyxu** [thepowersgang/mrustc#272]
```
fn main() {
  let a = (-75546505494413382671545042043112554817_i128).wrapping_mul(4);
  println !("{}", a)
}
```
Expected output:
38096344943284932777194439259317992188

Actual output:
-38096344943284932777194439259317992188

```
fn main() {
  let a = (-75546505494413382671545042043112554817_i128).wrapping_div(4);
  println !("{}", a)
}
```
Expected output:
-18886626373603345667886260510778138704

Actual output:
18886626373603345667886260510778138704

The mul and div operators seem to work fine and overflow as expected.

**Comment by thepowersgang** [comment]
Same as #271 - A bug in runtime i128 handling
