### ISSUE TITLE
Parsing error for struct member initializations

### ISSUE THREAD

**Issue by mayanksharma3** [thepowersgang/mrustc#274]
Hi, 

I'm in the (fairly early) process of building a Rust fuzzer ([here](https://github.com/rustsmith/rustsmith)) and whilst running it, I found that there was a parsing error for struct member initializations. I have reduced the file down to the following program:

```rust
struct Struct1 {
    var1: usize,
}

fn main() -> () {
    Struct1 {
        var1: { vec![1i16] }.len(),
    };
}
```

The expectation is: no compilation error

The result was: Compilation error (as shown below)

```
bug.rs:7: error:0:Unexpected token TOK_DOT, expected TOK_COMMA
```

**Comment by thepowersgang** [comment]
Looks like it's caused by calling `Parse_Stmt` instead of `Parse_Expr0` for values here.
