### ISSUE TITLE
Suggestion to make rustc-nightly fetch in Makefile optional (and more)

### ISSUE THREAD

**Issue by ng-0** [thepowersgang/mrustc#29]
About RUSTSRC in Makefile (https://github.com/thepowersgang/mrustc/blob/master/Makefile#L168):

This will not work in most sane build environments. Most operating systems will have to fetch rustc-nightly in advance due to isolated build-environments. I suggest to remove the rule and check for a local file, or anything similar (better yet, but I'm not a rust dev: try to implement tests without dependency on rustc-nightly). For example for GNU Guix I will fetch the rustc-nightly tarball as a separate file before the build starts.

I'm really looking forward where this project is going, with the bootstrapping issue of rustc (rustc requiring rustc for build).
As far as I understand mrustc, just taking a first short look at the code, it only requires the rustc-nightly source for tests, correct?

**Comment by thepowersgang** [comment]
It doesn't require the source to compile mrustc itself, but it needs it to be able to compile any executables (for libstd).

**Comment by thepowersgang** [comment]
Note - The source download shouldn't be done if the tarball is newer than the file `rust-version`

**Comment by thepowersgang** [comment]
Download is optional now (triggered by running `make RUSTCSRC`
