### ISSUE TITLE
[Question] Does mrustc makes programs in Rust more portable across host/platforms that LLVM doesn't cover?

### ISSUE THREAD

**Issue by alpominth** [thepowersgang/mrustc#303]
GCC supports many targets when doing cross-compiling, I believe even more than LLVM.

Let's suppose I want to redistribute a binary of my program and one of the targets I want is not covered by LLVM.

Could I just compile my project with mrustc, compile the generated C code and redistribute?

Or will there be problems with compilation or something like this?

**Comment by thepowersgang** [comment]
Thanks for waiting (I've been distracted with playing Zelda)
Compilation should work, once a target definition TOML file is added, but the standard library (including libcore) may need patching.

You're welcome to try, although be aware that mrustc's code generation isn't the best.

**Comment by alpominth** [comment]
>but the standard library (including libcore) may need patching.

Do you mean that libstd needs to be ported to a specific platform that LLVM doen't has support for but GCC does?

**Comment by bjorn3** [comment]
Yes, libstd generally needs modifications to support new targets. By the way have you seen https://github.com/rust-lang/rustc_codegen_gcc/? This is a GCC backend for the official rust compiler.

**Comment by alpominth** [comment]
No Man, I didn't know that project, starred and I'm watching it.

I was thinking on choosing Go as my breadwinner programming language, but now I'm sure that Rust is the right language. I know that GCC-GO exists, but it doesn't have support for generics.

Thank you very much for sharing this information.

Have a so so nice day!
