### ISSUE TITLE
Add PGO support

### ISSUE THREAD

**Issue by zamazan4ik** [thepowersgang/mrustc#304]
Since the upstream `rustc` [supports](https://blog.rust-lang.org/inside-rust/2020/11/11/exploring-pgo-for-the-rust-compiler.html) PGO and clang gains benefits from PGO [too](https://llvm.org/docs/HowToBuildWithPGO.html) I think would be a good idea to provide PGO build variant to `mrustc` as well.

**Comment by thepowersgang** [comment]
Would that mean mrustc itself built using PGO, or the rustc built by mrustc using PGO?

I've never worked with PGO, so cannot comment as to the ease of either - but speed isn't really the goal of mrustc, correctness is.

**Comment by zamazan4ik** [comment]
> Would that mean mrustc itself built using PGO, or the rustc built by mrustc using PGO?

Building `mrustc` with PGO.

> but speed isn't really the goal of mrustc, correctness is.

PGO does not affect the correctness of a program - just a performance improvement.

> I've never worked with PGO

I suggest starting with the documentation for your compiler. E.g. for Clang the documentation is [here](https://clang.llvm.org/docs/UsersManual.html#profile-guided-optimization). More materials about PGO (results, more advanced techniques like LLVM BOLT, possibly helpful notes) are [here](https://github.com/zamazan4ik/awesome-pgo/). I hope it helps.

**Comment by thepowersgang** [comment]
I'll rephrase my previous comment - My personal focus is on getting mrustc to correctly produce code, not to focus on making it fast.

I wouldn't be too against someone else experimenting with PGO and seeing if it improves performance enough to be worth including.
