### ISSUE TITLE
Parallel builds

### ISSUE THREAD

**Issue by orowith2os** [thepowersgang/mrustc#307]
mrustc currently supports parallel builds, but has some issues.

From the IRC:

> although I don't use it by default, still some minor issues in minicargo's logic
> (it'll sometimes fail to compile due to races somewhere)

See https://github.com/thepowersgang/mrustc/issues/225

Should maybe look into what, exactly, is causing these build errors; the linked issue says:

> Might be an issue with running with -j caused by bad dependency rules inside the makefile (leading to two copies of minicargo trying to build the same crates)

Some form of syncing (or something) would be ideal, if this fixes the issue. It would make it less dangerous to do parallel builds.

**Comment by thepowersgang** [comment]
Testing locally on windows hasn't had any issues... it might be that the problems I saw originally were due to memory exhaustion - some crates take a LOT of ram to compile.

**Comment by orowith2os** [comment]
How many CPU threads do you have? Could be that it only happens at a certain point. 

I don't think it's memory, because mine was just fine when using this, iirc.

I'm not at home, so I might not be able to provide many meaningful contributions for now.

**Comment by thepowersgang** [comment]
Closing as fixed, as #316 has been merged.
