### ISSUE TITLE
Compilation Error: Failed to find IntoIterator implementation for `core-0_0_0`

### ISSUE THREAD

**Issue by iamanonymouscs** [thepowersgang/mrustc#317]
I encountered an error while compiling a Rust program using mrustc. The code and error message is as follows
# Code
```rust
fn main() {
    let arr = [0; 10];
    for i in arr {
        println!("{}", i)
    }
}
```
# Error Output
```sh
:0:0 error:0:Failed to find an impl of ::"core-0_0_0"::iter::traits::IntoIterator for [_/*36:i*/; 10]
Aborted (core dumped)
```
However, the code can be compiled successfilly by rustc(stable 1.72).

**Comment by thepowersgang** [comment]
mrustc only supports up to rust 1.54.0, and then only when explicitly asked to build it. The default is (for legacy reasons) 1.29

Look at the `build-1.54.0.sh` script for the commands to build for a more recent version.
