### ISSUE TITLE
Compilation Error: BUG in expr_cs.cpp:7534 - Spare rules left after typecheck stabilised

### ISSUE THREAD

**Issue by iamanonymouscs** [thepowersgang/mrustc#318]
I encountered an error while compiling the following code using mrustc🤣However, yhis code can be compiled successfully by rustc(1.29) without any warning~ 
I'm unsure whether the cause of this issue is an internal error within mrustc or if mrustc lacks support for certain Rust language features. If there are more detailed reference materials available that could be provided to me, I would greatly appreciate it.😉
# Code
```rust
use std::env;

fn main() {
    let args: Vec<String> = env::args().collect();

    match args.len() {
        1 => {
            match args[1].parse() {
                Ok(42) => println!("branch ok(42)"),
                _ => println!("branch _"),
            }
        },
        _ => {
            // code
           
        }
    }
}

```
# Output

```sh

find.rs:12:1 warn:0:Spare Rule - _/*11*/ = < _/*47*/ as ::"core-0_0_0"::str::FromStr >::Err
find.rs:8:35 warn:0:Spare Rule - _/*47*/ : ::"core-0_0_0"::str::FromStr
find.rs:12:1 warn:0:Spare Rule - MatchErgonomicsRevisit { 42 : _/*47*/ }
:0:0 BUG:src/hir_typeck/expr_cs.cpp:7534: Spare rules left after typecheck stabilised

```

**Comment by thepowersgang** [comment]
It's a bug in mrustc - looks like it's unable to propagate that the result of `.parse` is a Result<i32` and thus stalls in type inference.

**Comment by thepowersgang** [comment]
Fixed in the above commit - While patterns did have integer type inference present, the annotation wasn't quite correct and thus it didn't work.
