### ISSUE TITLE
::std::strchr return type differs from ::std::string position arg

### ISSUE THREAD

**Issue by kallisti5** [thepowersgang/mrustc#32]
in src/main.cpp, line 728:

```c++
auto* pos = ::std::strchr(desc, '=');
```

a few lines later:
```c++
auto name = ::std::string(desc, pos);
```

compiler throws an error:
```
src/main.cpp:728:52: error: Invalid conversion from 'char*' to 'std::basic_string<char>::size_type {aka long unsigned int}'
```
Changing pos to *pos makes it compile here, but not sure if that is the correct solution.

**Comment by ubsan** [comment]
The correct way to do this is `pos - desc`. This looks a `permissive` issue - MSVC should use `/permissive-`, while gcc and clang should use `-pedantic`>

**Comment by thepowersgang** [comment]
Hmm... the intention of that call was to use the iterator version of the `std::string` constructor. What compiler are you using here?

**Comment by ubsan** [comment]
huh, that's really weird. I'm also curious, that looks like a bug.
