### ISSUE TITLE
How to use mrustc to build this project?

### ISSUE THREAD

**Issue by vmz9poa5** [thepowersgang/mrustc#331]
https://github.com/IsaacShelton/Adept3x

**Comment by bjorn3** [comment]
You almost certainly want to bootstrap the official rustc using mrustc and then build the project using the rustc you built. Mrustc lags behind rustc and mostly omits things not necessary for bootstrapping rustc itself. For exanple async/await is missing.

**Comment by vmz9poa5** [comment]
You don't want to be a full alternative to rustc? I can assume the code is good as it built with rustc. I only want to have the binary, so I don't care about the quality of the error messages by mrustc (which is terrible as you described).

**Comment by thepowersgang** [comment]
There are basic instructions on how to use mrustc to build non-rustc code in the readme... but be warned, it's not what mrustc is tested for.

For that project, it may work... or it may not, depends on the features it uses.
