### ISSUE TITLE
Mrustc 0.11.0 fails to build cargo 1.74.0's orion dependency

### ISSUE THREAD

**Issue by dtolnay** [thepowersgang/mrustc#346]
I ran the following from a Debian 13 host:

```bash
export LIBSSH2_SYS_USE_PKG_CONFIG=true
export MRUSTC_TARGET_VER=1.74
export PARLEVEL="$(nproc)"
export RUSTC_VERSION=1.74.0
make -j$(nproc) -f minicargo.mk bin/mrustc
make -j$(nproc) -f minicargo.mk RUSTCSRC
make -j$(nproc) -f minicargo.mk output-1.74.0/rustc
make -j$(nproc) -f minicargo.mk output-1.74.0/cargo
```

`mrustc` and `rustc` build successfully. The output shows:

```console
Completed rustc-main v0.0.0 [bin rustc_main]
 (100.0% 0r,0w,0b,304c/304t):
```

However, `cargo` (the last `make` command) fails to build.

This is the relevant part of the log I can find:

`rustc-1.74.0-src/vendor/orion/src/hazardous/hash/sha2/sha384.rs:94:1 error:0:Value mismatch between Evaluated(5000000000000000{}) and Unevaluated({0=1=}bb0:{ retval = Constant(::"orion-0_17_4"::hazardous::hash::sha2::sha512::N_CONSTS); Return })`
`Process was terminated with signal 6`
`FAILING COMMAND: /build/mrustc-0.11.0/bin/mrustc rustc-1.74.0-src/vendor/orion/src/lib.rs -o output-1.74.0/cargo-build/liborion-0_17_4.rlib -C emit-depfile=output-1.74.0/cargo-build/liborion-0_17_4.rlib.d --cfg debug_assertions -O -L output-1.74.0 -L output-1.74.0/cargo-build --crate-name orion --crate-type rlib --crate-tag 0_17_4 --edition 2021 --extern fiat_crypto=output-1.74.0/cargo-build/libfiat_crypto-0_1_20.rlib --extern subtle=output-1.74.0/cargo-build/libsubtle-2_5_0_H4.rlib --extern zeroize=output-1.74.0/cargo-build/libzeroize-1_6_0_H2.rlib`
`Env:  OUT_DIR=/build/mrustc-0.11.0/output-1.74.0/cargo-build/build_orion-0_17_4 CARGO_MANIFEST_DIR=/build/mrustc-0.11.0/rustc-1.74.0-src/vendor/orion CARGO_PKG_NAME=orion CARGO_PKG_VERSION=0.17.4 CARGO_PKG_VERSION_MAJOR=0 CARGO_PKG_VERSION_MINOR=17 CARGO_PKG_VERSION_PATCH=4`

**Comment by dtolnay** [comment]
Notice that 2 different `N_CONSTS` constants are in play, one in `hazardous::hash::sha2::sha384` and the other `hazardous::hash::sha2::sha512`. They both have the value 80.

- https://github.com/orion-rs/orion/blob/0.17.4/src/hazardous/hash/sha2/sha384.rs#L86-L93
- https://github.com/orion-rs/orion/blob/0.17.4/src/hazardous/hash/sha2/sha512.rs#L86-L95

Having the same value of 80 is the reason that `const K: [WordU64; N_CONSTS] = super::sha512::V512::K` in `sha384` is supposed to work.

**Comment by dtolnay** [comment]
This might be a nondeterministic failure. I tried running `make -j$(nproc) -f minicargo.mk output-1.74.0/cargo` repeatedly and it failed 14 times in a row as above, then succeeded on the 15th time. On a different machine, I ran it 60 times and all failed.

**Comment by thepowersgang** [comment]
It is nondeterministic, it was an uninitialised member variable that used to be consistently zero (the intended value), but now sometimes ends up being nonzero and thus changes the behavior of constant evaluation.
