### ISSUE TITLE
Question: Do you think it'd be feasible to write a minimal C++ to C compiler in C for mrustc?

### ISSUE THREAD

**Issue by tbu-** [thepowersgang/mrustc#348]
This would allow to bootstrap Rust without a dependency on an actual C++ compiler, but I'm not sure whether that'd be easier than the [Dozer](https://notgull.net/announcing-dozer/) project or not.

(This would require that the Rust compiler can be built without dependency on C++ libraries, which I'm not too sure about. You can see that I didn't do my research. My gut feeling says there's the cranelift backend, but I neither know whether it can be used to bootstrap Rust itself, nor do I know whether the LLVM backend can be configured out.)

If you'd like to not answer questions via this venue, feel free to close this. (This is definitely not meant as a request for you to write that C++ to C compiler.)

**Comment by thepowersgang** [comment]
It's probably doable, although I've always used the llvm rust backend (due to continuing to partially support versions before cranelift was added.

**Comment by tbu-** [comment]
Thanks. I'm probably still heavily underestimating the amount of work required to produce a C++ to C compiler capable of compiling mrustc. :)
