### ISSUE TITLE
Error compiling.

### ISSUE THREAD

**Issue by aristarh2704** [thepowersgang/mrustc#35]
I tried build mrustc on cygwin. There was an error:
src/main.cpp:744:52: error: no matching function for call to 'std::basic_string<char>::basic_string(const char*&, char*&)'
                 auto name = ::std::string(desc, pos);
..............................
src/main.cpp:744:52: error: invalid conversion from 'char*' to 'char' [-fpermissive]
                 auto name = ::std::string(desc, pos);

I was able to fix it by changing src / main.cpp: 744: "pos" -> "* pos".

**Comment by thepowersgang** [comment]
Duplicate of #32
