### ISSUE TITLE
Fails to build under armv7l

### ISSUE THREAD

**Issue by devrandom** [thepowersgang/mrustc#38]
During `make -f minicargo.mk`, gcc complains about `__int128` not being supported when compiling `libcore.hir.o.c`.

**Comment by thepowersgang** [comment]
Hmm... sounds like there needs to be a new target defined for ARM64 that turns on 128 bit integer emulation. (Note, currently only x86-64 is supported as a target)

**Comment by devrandom** [comment]
Strange, searching Google for `arm64 __int128` returns hits implying that it should work on gcc-5.  I wonder if a later version will help.  I'm only tried 5.4.

**Comment by devrandom** [comment]
My mistake, I was running on a 32 bit ARM CPU, not arm64.

**Comment by devrandom** [comment]
I don't have the target board available anymore, so can't test.  I think this can be closed.
