### ISSUE TITLE
Fails to build under aarch64 (ARM 64 bit)

### ISSUE THREAD

**Issue by devrandom** [thepowersgang/mrustc#39]
Fails on the following step:

```
odroid@odroid64:~/mrustc$ "gcc" "-ffunction-sections" "-pthread" "-O2" "-g" "-o" "output/libcore.hir.o" "output/libcore.hir.o.c" "-c"
/tmp/ccFfliuA.s: Assembler messages:
/tmp/ccFfliuA.s:17954: Error: unknown mnemonic `pause' -- `pause'
```

which is caused by:

```
output/libcore.hir.o.c: __asm__ __volatile__("pause": : : "memory");
```

Any ideas how to work around?

**Comment by thepowersgang** [comment]
Add support for ARM as a target? The only targets supported at the moment are x86-64 and partial x86 support (due to inline assembly and pointer sizes)

**Comment by daym** [comment]
(The inline assembly is fine, right? I mean inline assembly is in the Rust libraries, right? The one for pause shouldn't have been taken because there's a guard:

`#[unstable(feature = "hint_core_should_pause", issue = "41196")]
pub fn hint_core_should_pause()
{
    #[cfg(any(target_arch = "x86", target_arch = "x86_64"))]
    unsafe {
        asm!("pause" ::: "memory" : "volatile");
    }

    #[cfg(target_arch = "aarch64")]
    unsafe {
        asm!("yield" ::: "memory" : "volatile");
    }
}`


)

I agree about the pointer sizes.

**Comment by thepowersgang** [comment]
An ARM64 target shouldn't be hard to add, but I do not have access to an ARM64 machine on which to test (and qemu is SLOW)

**Comment by jirutka** [comment]
We have some free credits from Scaleway for Alpine Linux, so I’ve prepared you temporary aarch64 machine for testing this: `thepowersgang@51.15.49.216` (login using your SSH key)

Unfortunately it’s running Ubuntu, Scaleway doesn’t support many distros for aarch64.

**Comment by thepowersgang** [comment]
Thanks. Looks like current master is building and running code (but when building rustc, hits #72)

**Comment by elichai** [comment]
@thepowersgang I found this looking possible support of non-x86 targets, does this mean mrustc supports aarch64 as a target? or that you can compile mrustc *to* aarch64? or both?
Thanks!

**Comment by thepowersgang** [comment]
Both... but testing is a little lacklustre.

**Comment by elichai** [comment]
what other targets are known to be supported (experimentally of course)
(FYI, travis now gives you arm64 and other architectures to test on https://docs.travis-ci.com/user/multi-cpu-architectures/#testing-on-multiple-cpu-architectures )

**Comment by andriuss-xilinx** [comment]
> @thepowersgang I found this looking possible support of non-x86 targets, does this mean mrustc supports aarch64 as a target? or that you can compile mrustc _to_ aarch64? or both?

Hmm, I found that I was hitting various issues on aarch64 (often rustc is compiled but building cargo fails).

**Comment by stikonas** [comment]
> @thepowersgang I found this looking possible support of non-x86 targets, does this mean mrustc supports aarch64 as a target? or that you can compile mrustc _to_ aarch64? or both?
> Thanks!

Hmm, I found that I was hitting various issues on aarch64 (often rustc is compiled but building cargo fails).
