### ISSUE TITLE
Gcc6.1 has a compile errors

### ISSUE THREAD

**Issue by Meai1** [thepowersgang/mrustc#4]
```
[pc@localhost mrustc]$ make
[CXX] -o .obj/ast/expr.o
src/ast/expr.cpp: In function ‘std::ostream& AST::operator<<(std::ostream&, const AST::ExprNode&)’:
src/ast/expr.cpp:44:5: error: nonnull argument ‘node’ compared to NULL [-Werror=nonnull-compare]
     if( static_cast<const void*>(&node) != nullptr ) {
     ^~
At global scope:
cc1plus: error: unrecognized command line option ‘-Wno-pessimizing-move’ [-Werror]
cc1plus: all warnings being treated as errors
make: *** [.obj/ast/expr.o] Error 1
```

2nd: (this happens all over the project, no idea what these empty if(0) are supposed to mean or do)

```
[CXX] -o .obj/hir/from_ast_expr.o
src/hir/from_ast_expr.cpp: In member function ‘virtual void LowerHIR_ExprNode_Visitor::visit(AST::ExprNode_BinOp&)’:
src/hir/from_ast_expr.cpp:158:90: error: this ‘if’ clause does not guard... [-Werror=misleading-indentation]
 AST::ExprNode_BinOp::CMPEQU :    op = ::HIR::ExprNode_BinOp::Op::CmpEqu ; if(0)
                                                                           ^~
```

**Comment by ubsan** [comment]
`if(0)` is intended to be an `if(false)`, for code that doesn't matter anymore.

**Comment by Meai1** [comment]
well it appears to be at the end of a case statement, so it doesnt do anything, not even for your purpose of commenting code out

**Comment by thepowersgang** [comment]
Ah - It's a code pattern, it's on the final case of a sequence that all share the same body. The next line is just a `;` - It's actually quite intentional, and possibly a false-positive for that lint...

**Comment by thepowersgang** [comment]
I've turned off `-Werror` in the makefile (well, made it conditional on being run by me... I'm lazy). This should mean that mrustc should compile on compatible compilers.

**Comment by thepowersgang** [comment]
Closing - Removal of `-Werror` should have fixed this.
