### ISSUE TITLE
output/libs doesn't seem to exist

### ISSUE THREAD

**Issue by coder543** [thepowersgang/mrustc#44]
In several places, such as `make test`, there are references to like `-L output/libs`, but that folder definitely doesn't exist on my machine after building `mrustc`. In `make test`, it also has `-L output`, and `output` has lots of libraries in it, so that makes sense. I feel like `-L output/libs` might be an obsolete flag?

It would be nice if the README documented how to compile code using `mrustc`. After observing how the Makefile is able to use `mrustc`, I figured it out, and it's bascially just

    mrustc hello.rs -L output

once all the paths are adjusted as appropriate.

I have not been able to figure out `minicargo`... it seems to just _do nothing_, and the output is always either completely empty, `Usage: minicargo <package dir>`, or `EXCEPTION: Unable to open file 'Cargo.toml'`. I haven't been able to get it to do _anything_ else.

**Comment by thepowersgang** [comment]
Thanks for pointing that out, it's residual code from before minicargo existed.

As to how to run mrustc, documentation is lacking, yes :)

Minicargo _should_ work if you point it at a directory containing Cargo.toml, but it doesn't support downloading packages, so will only work if you either have vendored the packages or if you don't use any crates.io dependencies.

**Comment by thepowersgang** [comment]
Dead directory reference removed in ad9ee752049e9e853adc634df66700dae573f8b8, closing. If you want live help with getting mrustc/minicargo working - ask in IRC - `irc.mozilla.org#mrustc`
