### ISSUE TITLE
I tried it on a sample main.rs program

### ISSUE THREAD

**Issue by Meai1** [thepowersgang/mrustc#5]
The output is always, even when i change some stuff in the rust file: 

[pc@localhost mrustc]$ ./bin/mrustc main.rs
Parse: V V V
(0.00 s) Parse: DONE
LoadCrates: V V V
(0.00 s) LoadCrates: DONE
Expand: V V V
:0: BUG:src/expand/mod.cpp:849: TODO: Expand - Load libstd
Aborted (core dumped)
[pc@localhost mrustc]$

**Comment by thepowersgang** [comment]
This project is nowhere near the stage of being able to compile a program - Currently it cannot load libstd or libcore (so only works for `#![no_core]` crates). I hope to reach that stage sometime this year, but that depends on free time.

**Comment by thepowersgang** [comment]
Closing for now as invalid.

**Comment by Meai1** [comment]
well can you add a little explanation of next steps, where the project has to go etc? basically what u just said only a little more.  I want to know the workflow, how do you know what to do next? how do you track features if at all? what's your first workable goal, like in 2 months to be able to compile a println!("hello world!");

**Comment by thepowersgang** [comment]
See the list of features and rough plans in the README, there's also a todo file in `Notes/`
