### ISSUE TITLE
Borrow checking with polonius? 

### ISSUE THREAD

**Issue by Restioson** [thepowersgang/mrustc#75]
Hi! Perhaps borrow checking could be implemented in future with use of [polonius](https://github.com/rust-lang-nursery/polonius), a library that models the borrow checker, if this is in scope/relevant. I thought that a reason that borrow checking isn't implemented in mrustc is the amount of work required to do it, but perhaps this library could assist with that?

**Comment by thepowersgang** [comment]
While that library may help with the actual borrowck implementation, most of the work (I think) is in propagating the lifetime annotations through (and doing region inference), after that the checks shouldn't be difficult.

**Comment by Restioson** [comment]
Yeah OK, fair
