### ISSUE TITLE
Generate headers

### ISSUE THREAD

**Issue by emosenkis** [thepowersgang/mrustc#76]
My current work on esp-rs requires using the generated C code as a library from a C++ shim. Any chance of mrustc generating headers? makeheaders was unable to do it adequately.

**Comment by thepowersgang** [comment]
It could, but wouldn't a better solution be a tool to make headers from rust exports? Why do you want the compiler to emit them?

**Comment by jrmuizel** [comment]
Yeah, it sounds like you should be using https://github.com/eqrion/cbindgen for this.

**Comment by emosenkis** [comment]
I'm trying cbindgen without much luck (it's only outputting declarations for one constant and one C function that's used by my Rust code, despite there being several other public types/functions in the crate).

In any case, I thought it would make sense for mrustc to generate the headers because only it knows what names it chose for types (with `#[no_mangle]` it will use the same name as in Rust, but that only seems to work for functions, not structs).

Using `makeheaders` on an altered version of the generated C code that doesn't use `$` in the names almost works, but it refuses to output struct definitions.

Directly `#include`-ing all of the generated C files almost works, but fails due to repeat definitions of a number of types.

Directly `#include`-ing the top-level crate's generated C and compiling the rest as a separate library almost works, but I'm currently getting linker errors - I'm not sure what the issue is or how viable fixing it would be.

I'd appreciate any advice on which direction to take.

**Comment by thepowersgang** [comment]
The "correct" solution would be to use cbindgen (and find out why it's not emitting those particular types).

The specifics of name mangling is (intended to be) an implementation detail, so using the generated C directly is very much liable to breakage.

**Comment by emosenkis** [comment]
I didn't have any luck getting what I needed from `cbindgen` but I did finally manage to get it to work by directly including the direct Rust dependency's generated C inside a `extern "C"` block, then compiling the rest of the generated C code separately and linking to it.
