### ISSUE TITLE
version tag for nicer build integration

### ISSUE THREAD

**Issue by TorstenScheck** [thepowersgang/mrustc#81]
I've successfully bootstrapped rust/cargo 1.20 and 1.21 using your compiler.
I'm extremely pleased, as this allows rust to be used in restrictive corporate environments.
Thank you very much for your work.

In order to integrate the bootstrap step, it would be nice, if this very usable state had a version number, so I don't have to resign to using a commit hash (which makes managers somehow uneasy).

Maybe you could even spare a version tag every other month? :-)

**Comment by thepowersgang** [comment]
I've added a version number report (`mrustc --version`) and tagged [v0.8.0](https://github.com/thepowersgang/mrustc/releases/tag/v0.8.0) in ec907f56199c495db061f2712a5be3977bcb11e8

Not sure about when I'll bump the number, probably when there's notable milestones
