### ISSUE TITLE
Compile rustc HEAD

### ISSUE THREAD

**Issue by DemiMarie** [thepowersgang/mrustc#93]
It would be nice if mrustc could compile rustc HEAD.

**Comment by arlied-google** [comment]
If nightly-1.29 were pushed to master, what's the latest Rust version that it could compile?

How much work is there to do on type inference?  I'm willing to put some time into it, myself.

**Comment by thepowersgang** [comment]
As the name suggests, it's targeting 1.29 (development of that branch is against 1.29 stable)

**Comment by DemiMarie** [comment]
Also, if I may ask, how hard would it be to add a borrow checker?

**Comment by thepowersgang** [comment]
Re the 1.29 branch, see #95

Re adding a borrow checker, not insurmountable but it would require quite a bit of work to propagate the lifetime annotations and do region inference.

**Comment by thepowersgang** [comment]
Closing, as targeting HEAD would be a futile effort (as it's always changing). The 1.29 branch is an effort to upgrade the target version to something more recent, and I predict a similar effort every year or so.
